//Item List
var loot = [
'Normal ;) - D.Va Voice Line',
'Normal ...Excuse Me - Winston Voice Line',
'Normal ...Punch - Spray ',
'Normal ^_^ - Mei Spray',
'Normal >_< - Mei Spray',
'Normal 512- Zarya Spray',
'Normal 76 - Soldier: 76 Spray',
'Normal A Chicken Out Of A Feather - Torbjorn Voice Line',
'Normal A New Challenger! - D.Va Voice Line',
'Normal A-Mei-Zing! - Mei Voice Line',
'Normal Acelerar - Lucio Spray',
'Normal Action - Ana Spray',
'Normal Action - Bastion Spray',
'Normal Adorable - Zenyatta Spray',
'Normal Aerial Superiority - Pharah Spray',
'Normal Aerial Superiority Achieved - Pharah Voice Line',
'Normal AFK - D.Va Voice Line',
'Normal Agent - Sombra Spray',
'Normal Agent - Symmetra Spray',
'Normal Ahhhh! - Junkrat Spray',
'Normal Aint I Killed You Before - McCree Voice Line',
'Normal Alexandra - Zarya Spray',
'Normal All Soldiers - Soldier: 76 Spray',
'Normal Amari - Pharah Spray',
'Normal American Hero - Soldier: 76 Spray',
'Normal Ana - Ana Spray',
'Normal Ana - Pharah Spray',
'Normal Angry - Winston Spray',
'Normal Anyone Want Some BBQ? - Junkrat Voice Line',
'Normal Ape Crossing - Winston Spray',
'Normal Archer - Hanzo Spray',
'Normal Architect - Symmetra Spray',
'Normal Are You Afraid? - Reinhardt Voice Line',
'Normal Armor - Torbjorn Spray',
'Normal Arrow - Mercy Spray',
'Normal Assassin - Genji Spray',
'Normal Aura - Zenyatta Spray',
'Normal Avenger - Zarya Spray',
'Normal Avenger (2) - Zarya Spray',
'Normal Aw Rubbish - Tracer Voice Line',
'Normal Aw Yeah! - D.Va Voice Line',
'Normal Baby - Winston Spray',
'Normal Badge - McCree Spray',
'Normal Baiser - Widowmaker Spray',
'Normal Baixo - Lucio Spray',
'Normal Balance - Zenyatta Spray',
'Normal BAMF - McCree Spray',
'Normal Banana - Winston Spray',
'Normal Bandage - Mercy Spray',
'Normal Bang - D.Va Spray',
'Normal Bang Bang - Junkrat Spray',
'Normal Bang! - McCree Spray',
'Normal Barrier - Reinhardt Spray',
'Normal Barrier - Zarya Spray',
'Normal Bass - Lucio Spray',
'Normal Battle Ready - Mercy Spray',
'Normal Be Right Back! - Tracer Voice Line',
'Normal Bear - Zarya Spray',
'Normal Beard - Torbjorn Spray',
'Normal Bearer - Ana Spray',
'Normal Beat The Heat - Mei Spray',
'Normal Beeple - Bastion Voice Line',
'Normal Behind You - Sombra Spray',
'Normal Behold - Symmetra Spray',
'Normal Black Widow - Widowmaker Spray',
'Normal Blackwatch - Reaper Spray',
'Normal Blaster - Mei Spray',
'Normal Blaster - Mercy Spray',
'Normal Blink - Tracer Spray',
'Normal Blocks - Bastion Spray',
'Normal Blood - Widowmaker Spray',
'Normal Blossom - Reaper Spray',
'Normal Blow It Up Again - Junkrat Voice Line',
'Normal Blueprint - Symmetra Spray',
'Normal Bombs Away! - Tracer Spray',
'Normal Boo Boo Doo De Doo - Bastion Voice Line',
'Normal Break It Down - Lucio Spray',
'Normal Breathin - Roadhog Spray',
'Normal Bring Me Another - Reinhardt Voice Line',
'Normal Brrring! - Junkrat Voice Line',
'Normal Bubble Gum - D.Va Spray',
'Normal Buckle - McCree Spray',
'Normal Builder - Symmetra Spray',
'Normal Bullet - McCree Spray',
'Normal Bunny - D.Va Spray',
'Normal Bunny (2) - D.Va Spray',
'Normal Bunny Hop - D.Va Spray',
'Normal Bweeeeeeeeee - Bastion Voice Line',
'Normal Calavarys Here - Tracer Spray',
'Normal Calavera - Sombra Spray',
'Normal Candy From A Baby - Roadhog Voice Line',
'Normal Cannon - Bastion Spray',
'Normal Cannon - Zarya Spray',
'Normal Cant Stop Wont Stop - Lucio Voice Line',
'Normal Car Wash - Symmetra Spray',
'Normal Carefree - Mei Spray',
'Normal Casual - Mei Spray',
'Normal Catch A Ride - Torbjorn Spray',
'Normal Catch Phrase! - Reinhardt Voice Line',
'Normal Catcher - Spray ',
'Normal Caution - Spray ',
'Normal Caution - Symmetra Spray',
'Normal Cereal - Lucio Spray',
'Normal Challenge - Hanzo Spray',
'Normal Champion - Zarya Spray',
'Normal Charge - Reinhardt Spray',
'Normal Check Me Out - Tracer Voice Line',
'Normal Cheer - Ana Spray',
'Normal Cheers - Tracer Spray',
'Normal Cheers Love - Tracer Spray',
'Normal Cheers Love! - Tracer Voice Line',
'Normal Chef - Torbjorn Spray',
'Normal Children Behave - Ana Voice Line',
'Normal Chill Out! - Mei Voice Line',
'Normal Chirr Chirr Chirr - Bastion Voice Line',
'Normal Claw - Torbjorn Spray',
'Normal Cloaked - Reaper Spray',
'Normal Clocks Tickin - Tracer Spray',
'Normal Cloud - Hanzo Spray',
'Normal Cobra - Pharah Spray',
'Normal Coin - Soldier: 76 Spray',
'Normal Come On! - Genji Voice Line',
'Normal Coming Up Explodey! - Junkrat Voice Line',
'Normal Completion Date? - Torbjorn Voice Line',
'Normal Concussive Blast - Pharah Spray',
'Normal Confident - Lucio Spray',
'Normal Confident - Mei Spray',
'Normal Confident - Tracer Spray',
'Normal Consultation Fee - Mercy Voice Line',
'Normal Contemplative - Zenyatta Spray',
'Normal Cool - Sombra Voice Line',
'Normal Cracked - Ana Spray',
'Normal Cracks - Reinhardt Spray',
'Normal Crazy - Junkrat Spray',
'Normal Crisis - Bastion Spray',
'Normal Crouch - Widowmaker Spray',
'Normal Crusader - Reinhardt Spray',
'Normal Crusader Online - Reinhardt Voice Line',
'Normal Crushing Machine - Reinhardt Voice Line',
'Normal Curious - Bastion Spray',
'Normal Current Outlook - Orisa Voice Line',
'Normal D.Va: 1 Bad Guys: 0 - D.Va Voice Line',
'Normal Damn! - Genji Voice Line',
'Normal Dance - Spray ',
'Normal Dark Overwatch - Spray ',
'Normal Dark Title - Spray ',
'Normal Dead Man Walking - Reaper Voice Line',
'Normal Deadeye - McCree Spray',
'Normal Deaf-Mute - Sombra Spray',
'Normal Death Blossom - Reaper Spray',
'Normal Death Comes - Reaper Spray',
'Normal Death Is Whimsical Today - Zenyatta Voice Line',
'Normal Deck - Lucio Spray',
'Normal Deep Thoughts - Roadhog Spray',
'Normal Defender - Zarya Spray',
'Normal Deja Vu - Tracer Voice Line',
'Normal Design - Symmetra Spray',
'Normal Detected - Widowmaker Spray',
'Normal Did You Mean To Do That? - Sombra Voice Line',
'Normal Die Die Die - Reaper Spray',
'Normal Discord - Zenyatta Spray',
'Normal Diva - D.Va Spray',
'Normal Dizzy - Mei Spray',
'Normal Do I Think? - Zenyatta Voice Line',
'Normal Do You Need A Hug? - Orisa Voice Line',
'Normal Doctors Orders - Mercy Voice Line',
'Normal Dont Get Caught - Torbjorn Voice Line',
'Normal Dont Get Me Angry - Winston Voice Line',
'Normal Dragon - Genji Spray',
'Normal Dragon - Hanzo Spray',
'Normal Dragonblade - Genji Spray',
'Normal Dragons - Hanzo Spray',
'Normal Dragonstrike - Hanzo Spray',
'Normal Draw - Genji Spray',
'Normal Draw - McCree Spray',
'Normal Drawn - Hanzo Spray',
'Normal Dun Dun Boop Boop - Bastion Voice Line',
'Normal Duty - Hanzo Spray',
'Normal Dweet Dweet Dweet! - Bastion Voice Line',
'Normal Earthshatter - Reinhardt Spray',
'Normal Efi Will Not Be Happy - Orisa Voice Line',
'Normal Emblem - Mercy Spray',
'Normal Emblem - Reinhardt Spray',
'Normal Emblem - Roadhog Spray',
'Normal Emblem - Widowmaker Spray',
'Normal Encore? - Widowmaker Voice Line',
'Normal Engineers - Torbjorn Voice Line',
'Normal Enigma - McCree Spray',
'Normal Enlightened - Zenyatta Spray',
'Normal Error: Sarcasm Module - Orisa Voice Line',
'Normal ES4 - Bastion Spray',
'Normal Everyone Dies - Ana Voice Line',
'Normal Everything By Design - Symmetra Voice Line',
'Normal Everywhere - Reaper Spray',
'Normal Explorer - Mei Spray',
'Normal Explorer - Winston Spray',
'Normal Exquisite - Symmetra Voice Line',
'Normal Eyepatch - Ana Spray',
'Normal Eyes - Mei Spray',
'Normal Eyes - Roadhog Spray',
'Normal Eyes - Sombra Spray',
'Normal Fareeha - Ana Spray',
'Normal Fastball - Winston Spray',
'Normal Fighter - Tracer Spray',
'Normal Fire at Will - Bastion Spray',
'Normal Fire Strike - Reinhardt Spray',
'Normal Fireball - Junkrat Spray',
'Normal Firework - Junkrat Spray',
'Normal Fist Bump - Zenyatta Spray',
'Normal Fix It Up - Torbjorn Spray',
'Normal Flight - Bastion Spray',
'Normal Flow - Zenyatta Spray',
'Normal Flow Like Water - Hanzo Voice Line',
'Normal Flower Power - Bastion Spray',
'Normal Flying Like An Egyptian - Pharah Voice Line',
'Normal Flying The Friendly Skies - Pharah Voice Line',
'Normal Focused - Zarya Spray',
'Normal Following My Programming - Orisa Voice Line',
'Normal Foot - Zenyatta Spray',
'Normal For You - Junkrat Spray',
'Normal Forged - Torbjorn Spray',
'Normal FOTS2 - Spray ',
'Normal Frag - Junkrat Spray',
'Normal Free Pig - Roadhog Spray',
'Normal Free Your Mind - Zenyatta Voice Line',
'Normal Fresh Meat - Roadhog Spray',
'Normal Frog - Lucio Spray',
'Normal From One Thing - Hanzo Voice Line',
'Normal Fuji - Spray ',
'Normal Fuse - Junkrat Spray',
'Normal Ganymede - Bastion Spray',
'Normal Gauze - Mercy Spray',
'Normal Gaze - Ana Spray',
'Normal Gaze - Widowmaker Spray',
'Normal Gears - Torbjorn Spray',
'Normal German Engineering - Reinhardt Voice Line',
'Normal Get Down Give Me 20 - Zarya Voice Line',
'Normal Get Off My Lawn - Soldier: 76 Voice Line',
'Normal Get Ready - Torbjorn Spray',
'Normal GG - D.Va Spray',
'Normal GG! - D.Va Voice Line',
'Normal Giant - Bastion Spray',
'Normal Give Me A Break - Reaper Voice Line',
'Normal Glitch In The System - Sombra Voice Line',
'Normal Glorious - Reinhardt Spray',
'Normal Glove - Symmetra Spray',
'Normal God of War - Genji Spray',
'Normal Goldshire Pictures - Spray ',
'Normal Good One - Sombra Voice Line',
'Normal Got Something To Say? - Roadhog Voice Line',
'Normal Got You On My Radar - Pharah Voice Line',
'Normal Gotcha - Roadhog Spray',
'Normal Grand Theft - Roadhog Spray',
'Normal Graphic - Zenyatta Spray',
'Normal Grave - Reaper Spray',
'Normal Grave - Soldier: 76 Spray',
'Normal Green Ninja - Genji Spray',
'Normal Grenade - Ana Spray',
'Normal Grin - Junkrat Spray',
'Normal Grin - Lucio Spray',
'Normal Grizzled - Soldier: 76 Spray',
'Normal Guardian - Ana Spray',
'Normal Guardian - Pharah Spray',
'Normal Gun Show - Zarya Spray',
'Normal Gunslinger - McCree Spray',
'Normal Guru - Zenyatta Spray',
'Normal Hack The Planet - Sombra Voice Line',
'Normal Hacked - Sombra Spray',
'Normal Hacked The Moon - Sombra Spray',
'Normal Hacker - Sombra Spray',
'Normal Hahaha! - Roadhog Voice Line',
'Normal Hairpin - Mei Spray',
'Normal Halo - Mercy Spray',
'Normal Hammer - Torbjorn Spray',
'Normal Hammer Down - Reinhardt Spray',
'Normal Hana - D.Va Spray',
'Normal Hand - Zenyatta Spray',
'Normal Haori - Hanzo Spray',
'Normal Happens To The Best Of Us - McCree Voice Line',
'Normal Happy Birthday! - Junkrat Voice Line',
'Normal Harmony - Zenyatta Spray',
'Normal Harold - Winston Spray',
'Normal Have A Nice Day! - Junkrat Voice Line',
'Normal Havent I Killed You - Reaper Voice Line',
'Normal Headset - D.Va Spray',
'Normal Heal Up - Soldier: 76 Spray',
'Normal Heart - D.Va Spray',
'Normal Hee Hoo Hoo - Bastion Voice Line',
'Normal Helix - Soldier: 76 Spray',
'Normal Hellfire - Reaper Spray',
'Normal Hello World! - Zenyatta Voice Line',
'Normal Helm - Reinhardt Spray',
'Normal Helmet - Roadhog Spray',
'Normal Here Piggy - Roadhog Spray',
'Normal Hero - Lucio Spray',
'Normal Heroes Never Die - Mercy Spray',
'Normal Hesitation - Ana Spray',
'Normal Hieroglyph - Pharah Spray',
'Normal High Noon - McCree Spray',
'Normal Hit Me! - Lucio Voice Line',
'Normal Hm... - Hanzo Voice Line',
'Normal Hogpower - Roadhog Spray',
'Normal Honor - Reinhardt Spray',
'Normal Honor And Glory - Reinhardt Voice Line',
'Normal Hooah - Soldier: 76 Spray',
'Normal Hooded - Reaper Spray',
'Normal Hook Line and Sinker - Roadhog Voice Line',
'Normal Hooked - Roadhog Spray',
'Normal Horizon - Winston Spray',
'Normal Horns - Reaper Spray',
'Normal Hot - Torbjorn Spray',
'Normal Hourglass - Widowmaker Spray',
'Normal How Barbaric - Mercy Voice Line',
'Normal How Embarrasing - Winston Voice Line',
'Normal How Unsightly - Symmetra Voice Line',
'Normal Huge Rez!! - Mercy Spray',
'Normal I Am Mother Russia - Zarya Voice Line',
'Normal I Can Bench More Than You - Zarya Voice Line',
'Normal I Could Do This All Day - Lucio Voice Line',
'Normal I Didnt Start This War... - Soldier: 76 Voice Line',
'Normal I Do Not Want A Banana - Winston Voice Line',
'Normal I Do What I Must - Hanzo Voice Line',
'Normal I Dont Think So - Symmetra Voice Line',
'Normal I Dreamt I Was A Butterfly - Zenyatta Voice Line',
'Normal I Play to Win - D.Va Voice Line',
'Normal I Think Therefor I am - Zenyatta Voice Line',
'Normal I Tried Being Reasonable - McCree Voice Line',
'Normal I Will Break You - Zarya Voice Line',
'Normal I Will Not Juggle - Zenyatta Voice Line',
'Normal Icon - Ana Spray',
'Normal Icon - Bastion Spray',
'Normal Icon - D.Va Spray',
'Normal Icon - Genji Spray',
'Normal Icon - Hanzo Spray',
'Normal Icon - Junkrat Spray',
'Normal Icon - Lucio Spray',
'Normal Icon - McCree Spray',
'Normal Icon - Mei Spray',
'Normal Icon - Mercy Spray',
'Normal Icon - Reaper Spray',
'Normal Icon - Reinhardt Spray',
'Normal Icon - Roadhog Spray',
'Normal Icon - Soldier: 76 Spray',
'Normal Icon - Sombra Spray',
'Normal Icon - Symmetra Spray',
'Normal Icon - Torbjorn Spray',
'Normal Icon - Tracer Spray',
'Normal Icon - Widowmaker Spray',
'Normal Icon - Winston Spray',
'Normal Icon - Zarya Spray',
'Normal Icon - Zenyatta Spray',
'Normal If It Lives I Can Kill It - Reaper Voice Line',
'Normal Illusive - Sombra Spray',
'Normal Im An Army Of One - Soldier: 76 Voice Line',
'Normal Im Back In Black - Reaper Voice Line',
'Normal Im Giving It All Ive Got! - Torbjorn Voice Line',
'Normal Im On Top Of The World - Lucio Voice Line',
'Normal Im Swedish - Torbjorn Voice Line',
'Normal Im The Quick - McCree Voice Line',
'Normal Impressive - Symmetra Voice Line',
'Normal In Concert - Lucio Spray',
'Normal In My Sights - Widowmaker Spray',
'Normal In Over Your Head - Sombra Voice Line',
'Normal In repairs - Bastion Spray',
'Normal Inner Fire - Zenyatta Spray',
'Normal Ironclad - Torbjorn Spray',
'Normal Is This Easy Mode? - D.Va Voice Line',
'Normal It Takes a Woman To Know It - Ana Voice Line',
'Normal Its The Little Things - Junkrat Voice Line',
'Normal Ive Got A Bullet - McCree Voice Line',
'Normal Jacket: 76 - Soldier: 76 Spray',
'Normal Jackpot! - Lucio Voice Line',
'Normal Je Te Vois - Widowmaker Spray',
'Normal Jesse - McCree Spray',
'Normal Junk - Junkrat Spray',
'Normal Just Squishing A Bug - Sombra Voice Line',
'Normal Justice Rains From Above - Ana Voice Line',
'Normal Justice... - Pharah Spray',
'Normal Kaboom - Junkrat Voice Line',
'Normal Kaboom! - Junkrat Spray',
'Normal Kambo - Lucio Spray',
'Normal Kanon - Torbjorn Spray',
'Normal Kaze No Gotoku - Genji Spray',
'Normal Keep Calm - Tracer Voice Line',
'Normal Key - Sombra Spray',
'Normal Kneeling - Hanzo Spray',
'Normal Kneeling - Tracer Spray',
'Normal Kneeling - Widowmaker Spray',
'Normal Knight - Reinhardt Spray',
'Normal Kumo - Hanzo Spray',
'Normal Learned Your Lesson - Mei Voice Line',
'Normal Leave This To A Professional - Pharah Voice Line',
'Normal Leave This To An Expert - Torbjorn Voice Line',
'Normal Leek - Spray ',
'Normal Left - Roadhog Spray',
'Normal Lena - Tracer Spray',
'Normal Let Them Eat Cake - Widowmaker Voice Line',
'Normal Lets Fight! - Genji Voice Line',
'Normal Lets Not Buy The Pig - Torbjorn Voice Line',
'Normal Letter - Ana Spray',
'Normal Lexigrams - Winston Spray',
'Normal License - Roadhog Spray',
'Normal Life is Pain So Is Death - Roadhog Voice Line',
'Normal Lift - Zarya Spray',
'Normal Light - Mercy Spray',
'Normal Light - Symmetra Spray',
'Normal Light Gun - D.Va Spray',
'Normal Lightning - Winston Spray',
'Normal Lines - Symmetra Spray',
'Normal Lion - Reinhardt Spray',
'Normal LOL - D.Va Voice Line',
'Normal Look For The Woman - Widowmaker Voice Line',
'Normal Lotus - Symmetra Spray',
'Normal Love DVa - D.Va Spray',
'Normal Lumerico - Spray ',
'Normal Lunge - Genji Spray',
'Normal Machine Pistol - Sombra Spray',
'Normal Mad - Junkrat Spray',
'Normal Magnifique - Widowmaker Voice Line',
'Normal Mako - Roadhog Spray',
'Normal Marionette - Sombra Spray',
'Normal Mask - Torbjorn Spray',
'Normal Mayhem - Junkrat Spray',
'Normal Measure Twice Cut Once - Genji Voice Line',
'Normal Medic - Mercy Spray',
'Normal Medical Assistance - Orisa Voice Line',
'Normal Meis Journal - Mei Spray',
'Normal Meka - D.Va Spray',
'Normal Mess With The Best... - Sombra Voice Line',
'Normal Mine - Junkrat Spray',
'Normal Mine! - Winston Spray',
'Normal Minefield - Junkrat Spray',
'Normal Miracle Worker - Mercy Voice Line',
'Normal Molten Core - Torbjorn Spray',
'Normal Moon - Hanzo Spray',
'Normal Mother Knows Best - Ana Voice Line',
'Normal Move! - Soldier: 76 Spray',
'Normal Muzzle - Soldier: 76 Spray',
'Normal My Analysis - Orisa Voice Line',
'Normal My Soul Seeks Balance - Genji Voice Line',
'Normal Nano Cola - D.Va Spray',
'Normal Natural Selection - Winston Voice Line',
'Normal Need A Second Opinion - Mercy Voice Line',
'Normal Need Personal Training? - Zarya Voice Line',
'Normal Nest - Bastion Spray',
'Normal Neural - Sombra Spray',
'Normal Never In Doubt - Hanzo Voice Line',
'Normal Never Second Best - Hanzo Voice Line',
'Normal Next - Reaper Voice Line',
'Normal Nin - Genji Spray',
'Normal Nin - Hanzo Spray',
'Normal Nine - Zenyatta Spray',
'Normal No Hacks Required - D.Va Voice Line',
'Normal No Mercy - Zarya Voice Line',
'Normal No Monkey Business - Winston Voice Line',
'Normal No One Escapes - Widowmaker Spray',
'Normal No Parking - Orisa Voice Line',
'Normal No Pork - Roadhog Spray',
'Normal No Scope Needed - Ana Voice Line',
'Normal Noire - Widowmaker Spray',
'Normal Noose - McCree Spray',
'Normal Not A Chance - Pharah Voice Line',
'Normal Not Good Enough - Genji Voice Line',
'Normal Not Hearing That Noise - Lucio Voice Line',
'Normal Not On My Watch - Soldier: 76 Voice Line',
'Normal Numbani Statue - Spray ',
'Normal Oh Yeah! - Lucio Voice Line',
'Normal Okay! - Mei Voice Line',
'Normal Old Soldier - Soldier: 76 Spray',
'Normal Old Soldiers - Soldier: 76 Voice Line',
'Normal Old Solider - Ana Spray',
'Normal Omnic - Bastion Spray',
'Normal Omnic Rights - Spray ',
'Normal On A Scale Of 1-10 - Mercy Voice Line',
'Normal On Call - Mercy Spray',
'Normal On Guard - Pharah Spray',
'Normal One Shot One Kill - Widowmaker Voice Line',
'Normal Ones and Zeroes - Zenyatta Voice Line',
'Normal Onmyodo - Genji Spray',
'Normal Ooh Shiny - Junkrat Voice Line',
'Normal Ooh-Ooo-Hoo-Hoo - Bastion Voice Line',
'Normal Oops - Reaper Spray',
'Normal Orange - Tracer Spray',
'Normal Orb - Zenyatta Spray',
'Normal Orbs - Zenyatta Spray',
'Normal Ouch Are You Okay? - Mei Voice Line',
'Normal Ouh La La - Widowmaker Voice Line',
'Normal Outlaw - McCree Spray',
'Normal Overgrown - Bastion Spray',
'Normal Overhead - Ana Spray',
'Normal Overwatch - Spray ',
'Normal Overwatch Title - Spray ',
'Normal Patched Up - Mercy Spray',
'Normal PB - Winston Spray',
'Normal Peace - Zenyatta Spray',
'Normal Peace And Blessings - Zenyatta Voice Line',
'Normal Peanut Butter? - Winston Voice Line',
'Normal Perfect Harmony - Symmetra Voice Line',
'Normal Pew! Pew! Pew! - Tracer Spray',
'Normal Photo - D.Va Spray',
'Normal Photograph - Ana Spray',
'Normal Piece Of Cake - Roadhog Voice Line',
'Normal Piggy - Roadhog Spray',
'Normal Pink - Zarya Spray',
'Normal Pistols - Tracer Spray',
'Normal Pixel Bunny - D.Va Spray',
'Normal Play Nice Play Pharah - Pharah Voice Line',
'Normal Play Pharah - Pharah Spray',
'Normal Popper - Roadhog Spray',
'Normal Popsicle - Mei Spray',
'Normal Portrait - Tracer Spray',
'Normal Portrait - Widowmaker Spray',
'Normal Pose - Symmetra Spray',
'Normal Poster - Tracer Spray',
'Normal Power - Sombra Spray',
'Normal Power Up! - D.Va Spray',
'Normal Precisely - Symmetra Voice Line',
'Normal Prepare Yourself! - Genji Voice Line',
'Normal Prepared - Genji Spray',
'Normal Primal Rage - Winston Spray',
'Normal Print - Mei Spray',
'Normal Projector - Symmetra Spray',
'Normal Psst - Reaper Spray',
'Normal Psychopath - Reaper Voice Line',
'Normal Pulse Bomb - Tracer Spray',
'Normal Pulse Rifle - Soldier: 76 Spray',
'Normal Pumped - Zarya Spray',
'Normal Push Off - Roadhog Voice Line',
'Normal Put You In Your Place - Symmetra Voice Line',
'Normal Puzzle - Sombra Spray',
'Normal Q.E.D. - Winston Spray',
'Normal Quien? - Sombra Spray',
'Normal Rage - Winston Spray',
'Normal Raptora - Pharah Spray',
'Normal Reach For The Sky - McCree Voice Line',
'Normal Reading - Mei Spray',
'Normal Ready For Action - Tracer Spray',
'Normal Ready To Work - Torbjorn Spray',
'Normal Reap On - Reaper Spray',
'Normal Reaping - Reaper Spray',
'Normal Recovery - Bastion Spray',
'Normal Remember This Moment - Hanzo Voice Line',
'Normal Research - Winston Spray',
'Normal Respect Your Elders - Reinhardt Voice Line',
'Normal Resurrect - Mercy Spray',
'Normal Retro - Bastion Spray',
'Normal Revenge - Reaper Spray',
'Normal Rhino - Spray ',
'Normal Rifle - Ana Spray',
'Normal Rifle: 76 - Soldier: 76 Spray',
'Normal Rikimaru - Spray ',
'Normal Roar - Reinhardt Spray',
'Normal Roar - Winston Spray',
'Normal Rocket Jump - Pharah Spray',
'Normal Rocket Jump? - Pharah Voice Line',
'Normal Rocket Launcher - Pharah Spray',
'Normal Rockets - Soldier: 76 Spray',
'Normal Royal - Reinhardt Spray',
'Normal Run! - Torbjorn Spray',
'Normal Ryugekiken - Genji Spray',
'Normal Sake - Hanzo Spray',
'Normal Sake! - Hanzo Voice Line',
'Normal Salt - D.Va Spray',
'Normal Salute - Pharah Spray',
'Normal Salute - Soldier: 76 Spray',
'Normal Salute - Tracer Spray',
'Normal Sarcophagus - Spray ',
'Normal Satya - Symmetra Spray',
'Normal Say Bacon... - Roadhog Voice Line',
'Normal Scarab - Pharah Spray',
'Normal Scarf - Hanzo Spray',
'Normal Science! - Winston Spray',
'Normal Scooter - Spray ',
'Normal Scope - Widowmaker Spray',
'Normal Scratch - Lucio Spray',
'Normal Scroll - Spray ',
'Normal Scythes - Reaper Spray',
'Normal Seal - Hanzo Spray',
'Normal Seen A Ghost? - Reaper Voice Line',
'Normal Sh-Sh-Sh - Bastion Voice Line',
'Normal Shaded - Tracer Spray',
'Normal Shadow - Ana Spray',
'Normal Shadow - Reaper Spray',
'Normal Shadow Step - Reaper Spray',
'Normal She Shoots She Scores - Tracer Voice Line',
'Normal Shh - Ana Spray',
'Normal Shield - Zarya Spray',
'Normal Shield Up - Reinhardt Spray',
'Normal Shimada - Genji Spray',
'Normal Shine Your Eyes - Orisa Voice Line',
'Normal Shot Down - Pharah Voice Line',
'Normal Show Me What You Got - Sombra Voice Line',
'Normal Show You How Its Done - Reinhardt Voice Line',
'Normal Shuriken - Genji Spray',
'Normal Shuriken (2) - Genji Spray',
'Normal Siberian Bear - Zarya Voice Line',
'Normal Sidearm - Ana Spray',
'Normal Siege Mode - Spray ',
'Normal Signature - Genji Spray',
'Normal Signature - Lucio Spray',
'Normal Signature (2) - Lucio Spray',
'Normal Silent - Reaper Spray',
'Normal Simple - Genji Voice Line',
'Normal Six-Gun Killer - Spray ',
'Normal Sketch - Mei Spray',
'Normal Skull - McCree Spray',
'Normal Skull - Sombra Spray',
'Normal Skull - Sombra Spray',
'Normal Skycode - Sombra Spray',
'Normal Smalt - Torbjorn Spray',
'Normal Smells Like Victory - Soldier: 76 Voice Line',
'Normal Smile - Junkrat Spray',
'Normal Smile - Mei Spray',
'Normal Smile - Mercy Spray',
'Normal Smile - Zarya Spray',
'Normal Smile! - Junkrat Voice Line',
'Normal Smoke - Junkrat Spray',
'Normal Sniper - Widowmaker Spray',
'Normal Snow Art - Mei Spray',
'Normal Snowball - Mei Spray',
'Normal Snowman - Mei Spray',
'Normal Soft Serve - Mei Spray',
'Normal Sol - Spray ',
'Normal Some Assembly Required - Torbjorn Voice Line',
'Normal Someone To Tuck You In? - Ana Voice Line',
'Normal Sorry About That! - Winston Voice Line',
'Normal Sorry But I Need To Jet - Pharah Voice Line',
'Normal Sorry Sorry Sorry Sorry - Mei Voice Line',
'Normal Soul - Genji Spray',
'Normal Soul Globe - Reaper Spray',
'Normal Soulstone - Spray ',
'Normal Spider - Widowmaker Spray',
'Normal Spin - Junkrat Spray',
'Normal Spin - Lucio Spray',
'Normal Spin - McCree Spray',
'Normal Spirit Dragon - Hanzo Voice Line',
'Normal Spray - Hanzo Spray',
'Normal Sprout - Bastion Spray',
'Normal Stance - Genji Spray',
'Normal Star - D.Va Spray',
'Normal Statue - Pharah Spray',
'Normal Stein - Reinhardt Spray',
'Normal Step Into My Parlor - Widowmaker Voice Line',
'Normal Step Into the Dojo - Hanzo Voice Line',
'Normal Stethoscope - Mercy Spray',
'Normal Sting - Mercy Spray',
'Normal Stoic - Genji Spray',
'Normal Stoic - Hanzo Spray',
'Normal Stoic - Torbjorn Spray',
'Normal Stone - Pharah Spray',
'Normal Strength - Zarya Spray',
'Normal Strike Commander - Soldier: 76 Spray',
'Normal Successor - Hanzo Spray',
'Normal Super! - Mercy Voice Line',
'Normal Superior - Sombra Spray',
'Normal Superior - Symmetra Spray',
'Normal Support - Mercy Spray',
'Normal Sure As Hell Aint Ugly - McCree Voice Line',
'Normal Surge - Zarya Spray',
'Normal Swing - Reinhardt Spray',
'Normal Swing - Widowmaker Spray',
'Normal Swing - Winston Spray',
'Normal Swiss - Mercy Spray',
'Normal Swords - Genji Spray',
'Normal Tag - Lucio Spray',
'Normal Tagged - Sombra Spray',
'Normal Tagged - Tracer Spray',
'Normal Tails - Roadhog Spray',
'Normal Take It Easy - McCree Spray',
'Normal Take Two - Mercy Voice Line',
'Normal Taking This Very Seriously - Sombra Voice Line',
'Normal Target - McCree Spray',
'Normal Target Practice - Genji Spray',
'Normal Tattoo - Pharah Spray',
'Normal Taunt - Zenyatta Spray',
'Normal Tea - Hanzo Spray',
'Normal Tekhartha - Zenyatta Spray',
'Normal That Does Not Compute - Orisa Voice Line',
'Normal That Was Great - Mei Voice Line',
'Normal Thats How It Is - Widowmaker Voice Line',
'Normal Thats Sir To You - Soldier: 76 Voice Line',
'Normal The Doctor Is In - Mercy Voice Line',
'Normal The Doctor Will See You - Mercy Voice Line',
'Normal The Iris Embraces You - Zenyatta Voice Line',
'Normal The Names - McCree Spray',
'Normal The Path - Symmetra Spray',
'Normal The Power Of Science! - Winston Voice Line',
'Normal The World Needs Heroes - Tracer Voice Line',
'Normal This Old Dog - Reinhardt Voice Line',
'Normal Throw - Zenyatta Spray',
'Normal Thumbs Up - McCree Spray',
'Normal Time To Kill - Reaper Spray',
'Normal Tinnitus - Lucio Voice Line',
'Normal To Life To Death - Widowmaker Voice Line',
'Normal Tobelstein - Zarya Spray',
'Normal Together - Zenyatta Spray',
'Normal Together We Are Strong - Zarya Voice Line',
'Normal Too Easy - Reaper Voice Line',
'Normal Toxic - Roadhog Spray',
'Normal Translocator - Sombra Spray',
'Normal Trapper - Junkrat Spray',
'Normal Triplo - Lucio Spray',
'Normal Tumbleweed - McCree Spray',
'Normal Turret - Torbjorn Spray',
'Normal Turrets - Torbjorn Spray',
'Normal Under Control - Lucio Spray',
'Normal Under Control - Tracer Voice Line',
'Normal Une Balle - Widowmaker Spray',
'Normal Unload - D.Va Spray',
'Normal Unlocked - Sombra Spray',
'Normal Upgradera - Torbjorn Spray',
'Normal Valkyrie - Mercy Spray',
'Normal Vaswani - Symmetra Spray',
'Normal Veuve - Widowmaker Spray',
'Normal Vigilant - Reinhardt Spray',
'Normal Vigilante - Soldier: 76 Spray',
'Normal Vigilante (2) - Soldier: 76 Spray',
'Normal Violence Is The Answer - Roadhog Voice Line',
'Normal Virus - Sombra Spray',
'Normal Vishkar - Symmetra Spray',
'Normal Visor - Soldier: 76 Spray',
'Normal Visor - Symmetra Spray',
'Normal Vives Adventure - Spray ',
'Normal Vroom! - Junkrat Spray',
'Normal Walk of Fame - D.Va Spray',
'Normal Walk Of Fame - Lucio Spray',
'Normal Walled - Mei Spray',
'Normal Wanderer - Hanzo Spray',
'Normal Wanted - Junkrat Spray',
'Normal Wanted - McCree Spray',
'Normal Wanted - Roadhog Spray',
'Normal Wanted - Soldier: 76 Spray',
'Normal Wanted: Dead Or Alive - McCree Voice Line',
'Normal Warrior - Genji Spray',
'Normal Was That All? - Reaper Voice Line',
'Normal Watching - D.Va Spray',
'Normal Wave - Lucio Spray',
'Normal We Are Strong - Zarya Spray',
'Normal We Have A Problem - Winston Voice Line',
'Normal Weaver - Symmetra Spray',
'Normal Web - Sombra Spray',
'Normal Wedjat - Ana Spray',
'Normal Wedjat - Pharah Spray',
'Normal Weights - Zarya Spray',
'Normal Welcome To My Reality - Symmetra Voice Line',
'Normal Welcome To The Gun Show - Zarya Voice Line',
'Normal Were All Animals - Roadhog Voice Line',
'Normal What Are You Lookin At? - Soldier: 76 Voice Line',
'Normal What Are You Thinking? - Ana Voice Line',
'Normal Whatcha Lookin At? - Tracer Spray',
'Normal Whats An Aimbot - Widowmaker Voice Line',
'Normal White - Reinhardt Spray',
'Normal White - Winston Spray',
'Normal Why Are You So Angry? - Lucio Voice Line',
'Normal Why Do You Struggle? - Symmetra Voice Line',
'Normal Widow - Widowmaker Spray',
'Normal Widows Kiss - Widowmaker Spray',
'Normal Wild Hog - Roadhog Spray',
'Normal Wilhelm - Reinhardt Spray',
'Normal Will - Symmetra Spray',
'Normal Wings - Mercy Spray',
'Normal Wings - Pharah Spray',
'Normal Wings - Tracer Spray',
'Normal Witness Me - Ana Voice Line',
'Normal Wood and Stone - Bastion Spray',
'Normal Working As Intended - Torbjorn Voice Line',
'Normal Wow - Winston Spray',
'Normal Wrestle - Reinhardt Spray',
'Normal Wrestle - Zarya Spray',
'Normal Wrist Launcher - Ana Spray',
'Normal Wrist Launcher - Pharah Spray',
'Normal Yay! - Mei Voice Line',
'Normal Yeah! - Genji Voice Line',
'Normal Yellow - Hanzo Spray',
'Normal You Are Only Human - Genji Voice Line',
'Normal You Didnt Make The Cut - Soldier: 76 Voice Line',
'Normal You Done? - McCree Voice Line',
'Normal You Gotta Believe! - Lucio Voice Line',
'Normal You Have To Let It Go - Mei Voice Line',
'Normal You Know Nothing - Ana Voice Line',
'Normal You Need A Time Out - Tracer Voice Line',
'Normal Your Face Here - McCree Spray',
'Normal Youre The Other One - Soldier: 76 Voice Line',
'Normal Ziegler - Mercy Spray',
'Normal Zwee? - Bastion Voice Line',
'Normal ZZZ - Ana Spray',
'Rare 50 Coins',
'Rare Activating Visor - Widowmaker Pose',
'Rare Air - Zenyatta Skin',
'Rare Amethyst - Pharah Skin',
'Rare Angelic - Mercy Pose',
'Rare Atmosphere - Winston Skin',
'Rare Azuki - Hanzo Skin',
'Rare Azul - Lucio Skin',
'Rare Azurite - Genji Skin',
'Rare Balance - Symmetra Pose',
'Rare Balance - Zenyatta Pose',
'Rare Banana - Winston Skin',
'Rare Beast - Winston Pose',
'Rare Birdwatching - Bastion Pose',
'Rare Bla - Torbjorn Skin',
'Rare Bleached - Junkrat Skin',
'Rare Blood - Reaper Skin',
'Rare Blueberry - D.Va Skin',
'Rare Brass - Reinhardt Skin',
'Rare Brick - Zarya Skin',
'Rare Cardamom - Symmetra Skin',
'Rare Carefree - Mercy Pose',
'Rare Casual - Mei Pose',
'Rare Casual - Reaper Pose',
'Rare Casual - Zarya Pose',
'Rare Celestial - Mercy Skin',
'Rare Check Out This Gun - Zarya Pose',
'Rare Chrysanthemum - Mei Skin',
'Rare Cidro - Sombra Skin',
'Rare Ciel - Widowmaker Skin',
'Rare Cinnabar - Genji Skin',
'Rare Citrine - Ana Skin',
'Rare Citron - Torbjorn Skin',
'Rare Cobalt - Reinhardt Skin',
'Rare Confident - Hanzo Pose',
'Rare Confident - Lucio Pose',
'Rare Confident - Reinhardt Pose',
'Rare Contemplative - McCree Pose',
'Rare Copper - Pharah Skin',
'Rare Copper - Reinhardt Skin',
'Rare Creation - Symmetra Pose',
'Rare Dance - Symmetra Pose',
'Rare Dawn - Bastion Skin',
'Rare Dawn - Orisa Skin',
'Rare Drowned - Junkrat Skin',
'Rare Earth - Zenyatta Skin',
'Rare Ebony - McCree Skin',
'Rare Electric Purple - Tracer Skin',
'Rare Emerald - Pharah Skin',
'Rare Enigmatic - Reaper Pose',
'Rare Fist Pump - Soldier: 76 Pose',
'Rare Flex - Orisa Pose',
'Rare Flex - Reinhardt Pose',
'Rare Flexing - Zarya Pose',
'Rare Forest - Winston Skin',
'Rare Garnet - Ana Skin',
'Rare Gaze - Widowmaker Pose',
'Rare Glasses - Winston Pose',
'Rare Goldenrod - Zarya Skin',
'Rare Gron - Torbjorn Skin',
'Rare Grooving - Lucio Pose',
'Rare Guardian - Pharah Pose',
'Rare Hacked - Sombra Pose',
'Rare Halt! - Orisa Pose',
'Rare Hammer - Torbjorn Pose',
'Rare Hands on Hips - Mei Pose',
'Rare Harmony - Zenyatta Pose',
'Rare Heliotrope - Mei Skin',
'Rare Hot Pink - Tracer Skin',
'Rare Hyacinth - Symmetra Skin',
'Rare I Heart You - D.Va Pose',
'Rare Incendio - Sombra Skin',
'Rare Irradiated - Junkrat Skin',
'Rare Itll Freeze That Way - Junkrat Pose',
'Rare Jade - Mei Skin',
'Rare Jet - Soldier: 76 Skin',
'Rare Jump Jet - Pharah Pose',
'Rare Kinoko - Hanzo Skin',
'Rare Kiwi - Roadhog Skin',
'Rare Kneeling - Genji Pose',
'Rare Kneeling - Hanzo Pose',
'Rare Kneeling - Junkrat Pose',
'Rare Kneeling - Mei Pose',
'Rare Kneeling - Pharah Pose',
'Rare Kneeling - Sombra Pose',
'Rare Lake - McCree Skin',
'Rare Laranja - Lucio Skin',
'Rare Leaf - Zenyatta Skin',
'Rare Legend - Reinhardt Pose',
'Rare Lemon-Lime - D.Va Skin',
'Rare Locked and Loaded - Soldier: 76 Pose',
'Rare Malachite - Genji Skin',
'Rare Mar - Sombra Skin',
'Rare Meadow - Bastion Skin',
'Rare Menacing - Reaper Pose',
'Rare Midnight - Reaper Skin',
'Rare Midori - Hanzo Skin',
'Rare Mission Complete - Ana Pose',
'Rare Mist - Mercy Skin',
'Rare Moss - Reaper Skin',
'Rare Mud - Roadhog Skin',
'Rare Neon Green - Tracer Skin',
'Rare Noche - Sombra Skin',
'Rare Nuit - Widowmaker Skin',
'Rare Nyah Nyah - Junkrat Pose',
'Rare Ochre - Genji Skin',
'Rare Olive - Soldier: 76 Skin',
'Rare Orchid - Mercy Skin',
'Rare Over the Shoulder - Hanzo Pose',
'Rare Over the Shoulder - McCree Pose',
'Rare Over the Shoulder - Tracer Pose',
'Rare Over the Shoulder - Widowmaker Pose',
'Rare Peace - D.Va Pose',
'Rare Peace - Zenyatta Pose',
'Rare Peridot - Ana Skin',
'Rare Persimmon - Mei Skin',
'Rare Plains - Orisa Skin',
'Rare Plommon - Torbjorn Skin',
'Rare Pointing to the Sky - Roadhog Pose',
'Rare Pop Up - Bastion Pose',
'Rare Protector - Ana Pose',
'Rare Ready for Action - Lucio Pose',
'Rare Ready for Battle - Mercy Pose',
'Rare Red Planet - Winston Skin',
'Rare Rising - Sombra Pose',
'Rare Rose - Widowmaker Skin',
'Rare Roxo - Lucio Skin',
'Rare Royal - Reaper Skin',
'Rare Royal Blue - Tracer Skin',
'Rare Russet - Soldier: 76 Skin',
'Rare Rusted - Junkrat Skin',
'Rare Saffron - Symmetra Skin',
'Rare Sage - McCree Skin',
'Rare Salute - Tracer Pose',
'Rare Sand - Roadhog Skin',
'Rare Seated - Ana Pose',
'Rare Shuriken - Genji Pose',
'Rare Sitting - D.Va Pose',
'Rare Sitting - Tracer Pose',
'Rare Sitting Pretty - Torbjorn Pose',
'Rare Sky - Bastion Skin',
'Rare Smoke - Soldier: 76 Skin',
'Rare Soldier - Soldier: 76 Pose',
'Rare Soot - Bastion Skin',
'Rare Sora - Hanzo Skin',
'Rare Sunrise - Orisa Skin',
'Rare Sword Stance - Genji Pose',
'Rare Taiga - Zarya Skin',
'Rare Take Five - Torbjorn Pose',
'Rare Take it Easy - McCree Pose',
'Rare Tangerine - D.Va Skin',
'Rare Tank - Bastion Pose',
'Rare Technomancer - Symmetra Skin',
'Rare The Thinker - Winston Pose',
'Rare Thistle - Roadhog Skin',
'Rare Thumbs Up - Roadhog Pose',
'Rare Titanium - Pharah Skin',
'Rare Tuckered Out - Roadhog Pose',
'Rare Turquoise - Ana Skin',
'Rare Twilight - Orisa Skin',
'Rare Vendant - Mercy Skin',
'Rare Vermelho - Lucio Skin',
'Rare Vert - Widowmaker Skin',
'Rare Violet - Zarya Skin',
'Rare Viridian - Reinhardt Skin',
'Rare Water - Zenyatta Skin',
'Rare Watermelon - D.Va Skin',
'Rare Wheat - McCree Skin',
'Epic ^o^ - D.Va Emote',
'Epic 150 Coins',
'Epic Alert! Alert! - Bastion Emote',
'Epic Amber - Mercy Skin',
'Epic Amused - Soldier: 76 Emote',
'Epic Amused - Sombra Emote',
'Epic Amusing - Genji Emote',
'Epic Anubis - Pharah Skin',
'Epic Applause - Mercy Emote',
'Epic Ascendant - Zenyatta Skin',
'Epic Askew - Symmetra Highlight',
'Epic At Rest - Widowmaker Emote',
'Epic Auditva - Lucio Skin',
'Epic Backflip - Hanzo Highlight',
'Epic Backflip - Tracer Highlight',
'Epic Barrage - Pharah Highlight',
'Epic Battle Angel - Mercy Highlight',
'Epic Beckon - Hanzo Emote',
'Epic Belly Laugh - Roadhog Emote',
'Epic Bone - Soldier: 76 Skin',
'Epic Boo! - Roadhog Emote',
'Epic Bring It On - Zarya Emote',
'Epic Brush Shoulder - Hanzo Emote',
'Epic Bullet Rain - Bastion Highlight',
'Epic Bundeswehr - Reinhardt Skin',
'Epic Bunny Hop - D.Va Emote',
'Epic Cackle - Reaper Emote',
'Epic Caduceus - Mercy Emote',
'Epic Camouflage - Orisa Skin',
'Epic Camouflage - Orisa Skin',
'Epic Can Crusher - Roadhog Emote',
'Epic Cant Deal - Junkrat Emote',
'Epic Capoeira - Lucio Emote',
'Epic Carbon Fiber - D.Va Skin',
'Epic Carbon Fiber - Genji Skin',
'Epic Cathode - Torbjorn Skin',
'Epic Challenge - Genji Emote',
'Epic Charge - Reinhardt Highlight',
'Epic Cheer - Orisa Emote',
'Epic Cheer - Pharah Emote',
'Epic Cheer - Tracer Emote',
'Epic Chilling - Lucio Emote',
'Epic Chortle - Bastion Emote',
'Epic Chrome - Genji Skin',
'Epic Chuckle - Hanzo Emote',
'Epic Chuckle - Pharah Emote',
'Epic Clap - Symmetra Emote',
'Epic Clicking Heels - Torbjorn Emote',
'Epic Cloud - Hanzo Skin',
'Epic Cobalt - Mercy Skin',
'Epic Comedy Gold - Zarya Emote',
'Epic Comedy Gold - Zarya Emote',
'Epic Companion - Mei Emote',
'Epic Crush You - Zarya Emote',
'Epic Curtain Call - Widowmaker Emote',
'Epic Cutting Edge - Genji Emote',
'Epic Dance - Symmetra Highlight',
'Epic Dawn - Zarya Skin',
'Epic Deadlift - Zarya Highlight',
'Epic Death Blossom - Reaper Highlight',
'Epic Defense Matrix - Bastion Skin',
'Epic Delighted - Widowmaker Emote',
'Epic Desert - Reaper Skin',
'Epic Desert - Winston Skin',
'Epic Disapproving - Ana Emote',
'Epic Dizzy - Bastion Emote',
'Epic Dragon - Hanzo Skin',
'Epic Drop The Beat - Lucio Highlight',
'Epic Earthen - Mei Skin',
'Epic Eject - D.Va Highlight',
'Epic Excuse Me - Winston Highlight',
'Epic Executioner - Reaper Highlight',
'Epic Fist - Soldier: 76 Emote',
'Epic Fisticuffs - Torbjorn Emote',
'Epic Flex - Reinhardt Emote',
'Epic Flourish - Pharah Emote',
'Epic Flow - Symmetra Emote',
'Epic Focused - Zenyatta Highlight',
'Epic Focusing - Zenyatta Emote',
'Epic Freestyle - Lucio Highlight',
'Epic Frosty :) - Mei Highlight',
'Epic Ganymede - Bastion Highlight',
'Epic Giggle - Mei Emote',
'Epic Glasses - Winston Highlight',
'Epic Glitch - Sombra Skin',
'Epic Going Up! - Mei Highlight',
'Epic Golden - Soldier: 76 Skin',
'Epic Guardian - Ana Highlight',
'Epic Guardian Angel - Mercy Highlight',
'Epic Guffaw - Torbjorn Emote',
'Epic Gunspinning - McCree Emote',
'Epic Hacking - Sombra Highlight',
'Epic Halt! - Orisa Emote',
'Epic Hammer Down - Reinhardt Highlight',
'Epic Hanging Around - Widowmaker Highlight',
'Epic Harmonious - Zenyatta Skin',
'Epic Harmony And Discord - Zenyatta Highlight',
'Epic Hat Tip - McCree Emote',
'Epic Headbanging - Roadhog Emote',
'Epic Heartbreaker - D.Va Emote',
'Epic Helix - Soldier: 76 Highlight',
'Epic Heroes Never Die - Mercy Highlight',
'Epic Hold On - Sombra Emote',
'Epic Horizon - Winston Skin',
'Epic I See You - Soldier: 76 Emote',
'Epic I See You... - Widowmaker Highlight',
'Epic Im Flying! - Junkrat Highlight',
'Epic In The Groove - Lucio Emote',
'Epic In The Groove - Lucio Highlight',
'Epic In Your Face - Torbjorn Highlight',
'Epic Insignificant - Symmetra Emote',
'Epic Jackal - Pharah Skin',
'Epic Jailbird - Junkrat Skin',
'Epic Joker - McCree Emote',
'Epic Juggling - Junkrat Emote',
'Epic Just In Time - Tracer Highlight',
'Epic Keeping You Safe - Orisa Highlight',
'Epic Kicking Dirt - Orisa Emote',
'Epic Knee Slapper - Lucio Emote',
'Epic Kneel - Mei Emote',
'Epic Kneel - Reinhardt Emote',
'Epic Knuckles - Pharah Emote',
'Epic Laughing - Tracer Emote',
'Epic Laughing Matter - Winston Emote',
'Epic Little Piggy - Roadhog Highlight',
'Epic Locked And Loaded - Soldier: 76 Emote',
'Epic Locked On - Ana Highlight',
'Epic Looking At You - Soldier: 76 Highlight',
'Epic Lounging - Junkrat Emote',
'Epic Lying Around - D.Va Highlight',
'Epic Masterpiece - Sombra Emote',
'Epic Maximum Charge - Zarya Highlight',
'Epic Meditate - Genji Emote',
'Epic Meditate - Hanzo Emote',
'Epic Meditate - Zenyatta Emote',
'Epic Meka Activated - D.Va Highlight',
'Epic Merciful- Ana Skin',
'Epic Midnight - Zarya Skin',
'Epic Mission Complete - Pharah Highlight',
'Epic Monkey Business - Winston Emote',
'Epic More Stretching Required - Reinhardt Highlight',
'Epic My Aim is True - Hanzo Highlight',
'Epic My Reality - Symmetra Highlight',
'Epic Nah! - Lucio Emote',
'Epic No Pulse - Mercy Emote',
'Epic Not Impressed - Ana Emote',
'Epic Not Impressed - Reaper Emote',
'Epic Oh! - Orisa Highlight',
'Epic Omnic Crisis - Bastion Skin',
'Epic On Guard - Bastion Highlight',
'Epic On The Range - McCree Skin',
'Epic OR15 - Orisa Skin',
'Epic Overload - Torbjorn Emote',
'Epic Paragon - Reinhardt Skin',
'Epic Party Time - D.Va Emote',
'Epic Patina - Widowmaker Skin',
'Epic Peanut Butter? - Winston Emote',
'Epic Pigpen - Roadhog Skin',
'Epic Posh - Tracer Skin',
'Epic Primal Rage - Winston Highlight',
'Epic Protector - Ana Emote',
'Epic Pulse - Sombra Highlight',
'Epic Pumping Iron - Zarya Emote',
'Epic Puppet - Junkrat Emote',
'Epic Refreshing - Torbjorn Highlight',
'Epic Regal - Symmetra Skin',
'Epic Relax - Mercy Emote',
'Epic Rest Mode - Bastion Emote',
'Epic Ride Em - Torbjorn Highlight',
'Epic Rip-Tire - Junkrat Highlight',
'Epic Roar - Winston Emote',
'Epic Robot - Bastion Emote',
'Epic Rolling Into Action - McCree Highlight',
'Epic Round Of Applause - Zenyatta Emote',
'Epic Salute - Genji Emote',
'Epic Say Cheese - Roadhog Highlight',
'Epic Serious Business - Tracer Highlight',
'Epic Shadow Step - Reaper Highlight',
'Epic Shh... - Ana Highlight',
'Epic Shot Dead - Widowmaker Emote',
'Epic Shrike - Ana Skin',
'Epic Shuriken - Genji Highlight',
'Epic Sitting Around - Winston Emote',
'Epic Sitting Around... - Tracer Emote',
'Epic Skating Around - Mei Highlight',
'Epic Slice - Reaper Emote',
'Epic Slow Clap - Reaper Emote',
'Epic Snicker - Symmetra Emote',
'Epic Snow Plum - Mei Skin',
'Epic Spin - Tracer Emote',
'Epic Spit - McCree Emote',
'Epic Sporty - Tracer Skin',
'Epic Spray - Mei Emote',
'Epic Stitched - Roadhog Skin',
'Epic Supercharger - Orisa Highlight',
'Epic Superior - Hanzo Highlight',
'Epic Swinging Into Action - Widowmaker Highlight',
'Epic Synaesthesia - Lucio Skin',
'Epic Take A Knee - Ana Emote',
'Epic Take A Knee - Pharah Emote',
'Epic Take A Knee - Reaper Emote',
'Epic Take A Knee - Soldier: 76 Emote',
'Epic Take A Knee - Zarya Emote',
'Epic Take A Knee - Zarya Emote',
'Epic Take A Load Off - McCree Emote',
'Epic Take A Seat - Symmetra Emote',
'Epic Taking A Break - Torbjorn Emote',
'Epic Target Rich Environment - Soldier: 76 Highlight',
'Epic Taunt - Reinhardt Emote',
'Epic Taunt - Zenyatta Emote',
'Epic Tea Time - Ana Emote',
'Epic The Best Medicine - Mercy Emote',
'Epic The Duel - McCree Highlight',
'Epic The Names McCree - McCree Highlight',
'Epic This Is Strength - Zarya Highlight',
'Epic Tickled - Zenyatta Emote',
'Epic Toasted - Junkrat Skin',
'Epic Touchdown - Pharah Highlight',
'Epic Transcendence - Zenyatta Highlight',
'Epic Tuckered Out - Roadhog Emote',
'Epic Undetected - Sombra Highlight',
'Epic Unfortunate - Junkrat Highlight',
'Epic Unsheathing the Sword - Genji Highlight',
'Epic Uproarious - Reinhardt Emote',
'Epic Utopaea - Symmetra Skin',
'Epic Vaudeville - Junkrat Emote',
'Epic Victory - Hanzo Emote',
'Epic Virus - Sombra Skin',
'Epic Warriors Salute - Genji Highlight',
'Epic Warriors Salute - Reinhardt Emote',
'Epic White Hat - McCree Skin',
'Epic White Rabbit - D.Va Skin',
'Epic Whole Hog - Roadhog Highlight',
'Epic Widows Kiss - Widowmaker Emote',
'Epic Wight - Reaper Skin',
'Epic Winter - Widowmaker Skin',
'Epic Woodclad - Torbjorn Skin',
'Epic Yaaaaaaaaaaay! - Mei Emote',
'Lgnd 500 Coins',
'Lgnd Abominable - Mei Skin',
'Lgnd Antique - Bastion Skin',
'Lgnd Architech - Symmetra Skin',
'Lgnd Arctic - Zarya Skin',
'Lgnd Augmented - Sombra Skin',
'Lgnd Azucar - Sombra Skin',
'Lgnd B.Va - D.Va Skin',
'Lgnd Balderich - Reinhardt Skin',
'Lgnd Barbarossa - Torbjorn Skin',
'Lgnd Bedouin - Genji Skin',
'Lgnd Blackbeard - Torbjorn Skin',
'Lgnd Blackhardt - Reinhardt Skin',
'Lgnd Bloodhardt - Reinhardt Skin',
'Lgnd Breakaway - Lucio Skin',
'Lgnd Captain Amari - Ana Skin',
'Lgnd Carbon Fiber - Orisa Skin',
'Lgnd Chopper - Torbjorn Skin',
'Lgnd Commando - Soldier: 76 Skin',
'Lgnd Comtesse - Widowmaker Skin',
'Lgnd Cyber Goth - Zarya Skin',
'Lgnd Cyberspace - Sombra Skin',
'Lgnd Daredevil - Soldier: 76 Skin',
'Lgnd Deadlock - Torbjorn Skin',
'Lgnd Devi - Symmetra Skin',
'Lgnd Devil - Mercy Skin',
'Lgnd Djinyatta - Zenyatta Skin',
'Lgnd Dynastinae - Orisa Skin',
'Lgnd El Blanco - Reaper Skin',
'Lgnd Explorer - Winston Skin',
'Lgnd Firefighter - Mei Skin',
'Lgnd Fool - Junkrat Skin',
'Lgnd Frogston - Winston Skin',
'Lgnd Gambler - McCree Skin',
'Lgnd Game On - D.Va Emote',
'Lgnd Gearbot - Bastion Skin',
'Lgnd Goddess - Symmetra Skin',
'Lgnd Greifhardt - Reinhardt Skin',
'Lgnd Hayseed - Junkrat Skin',
'Lgnd Hippityhop - Lucio Skin',
'Lgnd Horus - Ana Skin',
'Lgnd Huntress - Widowmaker Skin',
'Lgnd Ifrit - Zenyatta Skin',
'Lgnd Imp - Mercy Skin',
'Lgnd Industrial - Zarya Skin',
'Lgnd Islander - Roadhog Skin',
'Lgnd Jester - Junkrat Skin',
'Lgnd Junebug - D.Va Skin',
'Lgnd Junker - D.Va Skin',
'Lgnd Lionhardt - Reinhardt Skin',
'Lgnd Lone Wolf - Hanzo Skin',
'Lgnd Los Muertos - Sombra Skin',
'Lgnd Mach T - Tracer Skin',
'Lgnd Mako - Roadhog Skin',
'Lgnd Mariachi - Reaper Skin',
'Lgnd Mechaqueen - Pharah Skin',
'Lgnd Megasoma - Orisa Skin',
'Lgnd Mystery Man - McCree Skin',
'Lgnd Nevermore - Reaper Skin',
'Lgnd Night Ops - Soldier: 76 Skin',
'Lgnd Nomad - Genji Skin',
'Lgnd Odette - Widowmaker Skin',
'Lgnd Odile - Widowmaker Skin',
'Lgnd Okami - Hanzo Skin',
'Lgnd Plague Doctor - Reaper Skin',
'Lgnd Protector - Orisa Skin',
'Lgnd Punk - Tracer Skin',
'Lgnd Ra - Zenyatta Skin',
'Lgnd Raindancer - Pharah Skin',
'Lgnd Raptorion - Pharah Skin',
'Lgnd Rescue Mei - Mei Skin',
'Lgnd Ribbit - Lucio Skin',
'Lgnd RiverBoat - McCree Skin',
'Lgnd Safari - Winston Skin',
'Lgnd Scarecrow - Junkrat Skin',
'Lgnd Scavenger - D.Va Skin',
'Lgnd Sharkbait - Roadhog Skin',
'Lgnd Siberian Front - Zarya Skin',
'Lgnd Sigrun - Mercy Skin',
'Lgnd Slapshot - Lucio Skin',
'Lgnd Sparrow - Genji Skin',
'Lgnd Steambot - Bastion Skin',
'Lgnd Stonehardt - Reinhardt Skin',
'Lgnd Stunt Rider - Soldier: 76 Skin',
'Lgnd Sunyatta - Zenyatta Skin',
'Lgnd T. Racer - Tracer Skin',
'Lgnd Thunderbird - Pharah Skin',
'Lgnd Toa - Roadhog Skin',
'Lgnd Ultraviolet - Tracer Skin',
'Lgnd Undersea - Winston Skin',
'Lgnd Valkyrie - Mercy Skin',
'Lgnd Vigilante - McCree Skin',
'Lgnd Vishkar - Symmetra Skin',
'Lgnd Wadjet - Ana Skin',
'Lgnd Wasteland - Ana Skin',
'Lgnd Woodbot - Bastion Skin',
'Lgnd Yeti Hunter - Mei Skin',
'Lgnd Young Genji - Genji Skin',
'Lgnd Young Hanzo - Hanzo Skin',
'Lgnd Young Master - Hanzo Skin'
];

//Item Weights
var weights = [
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2
];