
//Item List
var loot = [
'Epic Alert! Alert! - Bastion Emote',
'Epic Dizzy - Bastion Emote',
'Epic Robot - Bastion Emote',
'Epic Bullet Rain - Bastion Highlight',
'Epic Ganymede - Bastion Highlight',
'Epic On Guard - Bastion Highlight',
'Epic Omnic Crisis - Bastion Skin',
'Epic Defense Matrix- Bastion Skin',
'LEGENDARY Steambot - Bastion Skin',
'LEGENDARY Woodbot - Bastion Skin',
'LEGENDARY Antique - Bastion Skin',
'LEGENDARY Gearbot - Bastion Skin',
'Normal Action - Bastion Spray',
'Normal Blocks - Bastion Spray',
'Normal Cannon - Bastion Spray',
'Normal Crisis - Bastion Spray',
'Normal Curious - Bastion Spray',
'Normal ES4 - Bastion Spray',
'Normal Fire at Will - Bastion Spray',
'Normal Flight - Bastion Spray',
'Normal Flower Power - Bastion Spray',
'Normal Ganymede - Bastion Spray',
'Normal Giant - Bastion Spray',
'Normal Icon - Bastion Spray',
'Normal In repairs - Bastion Spray',
'Normal Nest - Bastion Spray',
'Normal Omnic - Bastion Spray',
'Normal Overgrown - Bastion Spray',
'Normal Recovery - Bastion Spray',
'Normal Retro - Bastion Spray',
'Normal Sprout - Bastion Spray',
'Normal Wood and Stone - Bastion Spray',
'Normal Beeple - Bastion Voice Line',
'Normal Boo Boo Doo De Doo - Bastion Voice Line',
'Normal Bweeeeeeeeee - Bastion Voice Line',
'Normal Chirr Chirr Chirr - Bastion Voice Line',
'Normal Dun Dun Boop Boop - Bastion Voice Line',
'Normal Dweet Dweet Dweet! - Bastion Voice Line',
'Normal Hee Hoo Hoo - Bastion Voice Line',
'Normal Ooh-Ooo-Hoo-Hoo- Bastion Voice Line',
'Normal Sh-Sh-Sh- Bastion Voice Line',
'Normal Zwee? - Bastion Voice Line',
'Rare Birdwatching - Bastion Pose',
'Rare Pop Up - Bastion Pose',
'Rare Tank - Bastion Pose',
'Rare Dawn - Bastion Skin',
'Rare Meadow - Bastion Skin',
'Rare Sky - Bastion Skin',
'Rare Soot - Bastion Skin',
'Epic Eject - D.Va Highlight',
'Epic Lying Around - D.Va Highlight',
'Epic Meka Activated - D.Va Highlight',
'Epic Carbon Fiber - D.Va Skin',
'Epic White Rabbit - D.Va Skin',
'LEGENDARY Junker - D.Va Skin',
'LEGENDARY B.Va - D.Va Skin',
'LEGENDARY Scavenger - D.Va Skin',
'LEGENDARY Junebug - D.Va Skin',
'Normal Bang - D.Va Spray',
'Normal Bubble Gum - D.Va Spray',
'Normal Bunny - D.Va Spray',
'Normal Bunny (2) - D.Va Spray',
'Normal Bunny Hop - D.Va Spray',
'Normal Diva - D.Va Spray',
'Normal GG - D.Va Spray',
'Normal Hana - D.Va Spray',
'Normal Headset - D.Va Spray',
'Normal Heart - D.Va Spray',
'Normal Icon - D.Va Spray',
'Normal Light Gun - D.Va Spray',
'Normal Love DVa - D.Va Spray',
'Normal Meka - D.Va Spray',
'Normal Nano Cola - D.Va Spray',
'Normal Photo - D.Va Spray',
'Normal Pixel Bunny - D.Va Spray',
'Normal Power Up! - D.Va Spray',
'Normal Salt - D.Va Spray',
'Normal Star - D.Va Spray',
'Normal Unload - D.Va Spray',
'Normal Walk of Fame - D.Va Spray',
'Normal Watching - D.Va Spray',
'Normal ;) - D.Va Voice Line',
'Normal A New Challenger! - D.Va Voice Line',
'Normal AFK - D.Va Voice Line',
'Normal Aw Yeah! - D.Va Voice Line',
'Normal D.Va: 1 Bad Guys: 0 - D.Va Voice Line',
'Normal GG! - D.Va Voice Line',
'Normal I Play to Win - D.Va Voice Line',
'Normal Is This Easy Mode? - D.Va Voice Line',
'Normal LOL - D.Va Voice Line',
'Normal No Hacks Required - D.Va Voice Line',
'Rare Bunny Hop - D.Va Emote',
'Rare Heartbreaker - D.Va Emote',
'Rare Party Time - D.Va Emote',
'Rare I Heart You - D.Va Pose',
'Rare Peace - D.Va Pose',
'Rare Sitting - D.Va Pose',
'Rare Blueberry - D.Va Skin',
'Rare Lemon-Lime- D.Va Skin',
'Rare Tangerine - D.Va Skin',
'Rare Watermelon - D.Va Skin',
'Epic Challenge - Genji Emote',
'Epic Cutting Edge - Genji Emote',
'Epic Salute - Genji Emote',
'Epic Shuriken - Genji Highlight',
'Epic Unsheathing the Sword - Genji Highlight',
'Epic Warriors Salute - Genji Highlight',
'Epic Carbon Fiber - Genji Skin',
'Epic Chrome - Genji Skin',
'LEGENDARY Sparrow - Genji Skin',
'LEGENDARY Young Genji - Genji Skin',
'LEGENDARY Bedouin - Genji Skin',
'LEGENDARY Nomad - Genji Skin',
'Normal Assassin - Genji Spray',
'Normal Dragon - Genji Spray',
'Normal Dragonblade - Genji Spray',
'Normal Draw - Genji Spray',
'Normal God of War - Genji Spray',
'Normal Green Ninja - Genji Spray',
'Normal Icon - Genji Spray',
'Normal Kaze No Gotoku - Genji Spray',
'Normal Lunge - Genji Spray',
'Normal Nin - Genji Spray',
'Normal Onmyodo - Genji Spray',
'Normal Prepared - Genji Spray',
'Normal Ryugekiken - Genji Spray',
'Normal Shimada - Genji Spray',
'Normal Shuriken - Genji Spray',
'Normal Shuriken (2) - Genji Spray',
'Normal Signature - Genji Spray',
'Normal Soul - Genji Spray',
'Normal Stance - Genji Spray',
'Normal Stoic - Genji Spray',
'Normal Swords - Genji Spray',
'Normal Target Practice - Genji Spray',
'Normal Warrior - Genji Spray',
'Normal Come On! - Genji Voice Line',
'Normal Damn! - Genji Voice Line',
'Normal Prepare Yourself! - Genji Voice Line',
'Normal Lets Fight! - Genji Voice Line',
'Normal Measure Twice Cut Once - Genji Voice Line',
'Normal My Soul Seeks Balance - Genji Voice Line',
'Normal Not Good Enough - Genji Voice Line',
'Normal Simple - Genji Voice Line',
'Normal Yeah! - Genji Voice Line',
'Normal You Are Only Human - Genji Voice Line',
'Rare Kneeling - Genji Pose',
'Rare Shuriken - Genji Pose',
'Rare Sword Stance - Genji Pose',
'Rare Azurite - Genji Skin',
'Rare Malachite - Genji Skin',
'Rare Ochre - Genji Skin',
'Rare Cinnabar - Genji Skin',
'Epic Beckon - Hanzo Emote',
'Epic Brush Shoulder - Hanzo Emote',
'Epic Victory - Hanzo Emote',
'Epic Backflip - Hanzo Highlight',
'Epic My Aim is True - Hanzo Highlight',
'Epic Superior - Hanzo Highlight',
'Epic Cloud - Hanzo Skin',
'Epic Dragon - Hanzo Skin',
'LEGENDARY Young Hanzo - Hanzo Skin',
'LEGENDARY Young Master - Hanzo Skin',
'LEGENDARY Lone Wolf - Hanzo Skin',
'LEGENDARY Okami - Hanzo Skin',
'Normal Archer - Hanzo Spray',
'Normal Challenge - Hanzo Spray',
'Normal Cloud - Hanzo Spray',
'Normal Dragon - Hanzo Spray',
'Normal Dragons - Hanzo Spray',
'Normal Dragonstrike - Hanzo Spray',
'Normal Drawn - Hanzo Spray',
'Normal Duty - Hanzo Spray',
'Normal Haori - Hanzo Spray',
'Normal Icon - Hanzo Spray',
'Normal Kneeling - Hanzo Spray',
'Normal Kumo - Hanzo Spray',
'Normal Moon - Hanzo Spray',
'Normal Nin - Hanzo Spray',
'Normal Sake - Hanzo Spray',
'Normal Scarf - Hanzo Spray',
'Normal Seal - Hanzo Spray',
'Normal Spray - Hanzo Spray',
'Normal Stoic - Hanzo Spray',
'Normal Successor - Hanzo Spray',
'Normal Tea - Hanzo Spray',
'Normal Wanderer - Hanzo Spray',
'Normal Yellow - Hanzo Spray',
'Normal Flow Like Water - Hanzo Voice Line',
'Normal From One Thing - Hanzo Voice Line',
'Normal Hm... - Hanzo Voice Line',
'Normal I Do What I Must - Hanzo Voice Line',
'Normal Never In Doubt - Hanzo Voice Line',
'Normal Never Second Best - Hanzo Voice Line',
'Normal Remember This Moment - Hanzo Voice Line',
'Normal Sake! - Hanzo Voice Line',
'Normal Spirit Dragon - Hanzo Voice Line',
'Normal Step Into the Dojo - Hanzo Voice Line',
'Rare Confident - Hanzo Pose',
'Rare Kneeling - Hanzo Pose',
'Rare Over the Shoulder - Hanzo Pose',
'Rare Azuki - Hanzo Skin',
'Rare Kinoko - Hanzo Skin',
'Rare Midori - Hanzo Skin',
'Rare Sora - Hanzo Skin',
'Epic Juggling - Junkrat Emote',
'Epic Puppet - Junkrat Emote',
'Epic Vaudeville - Junkrat Emote',
'Epic Im Flying! - Junkrat Highlight',
'Epic Rip-Tire- Junkrat Highlight',
'Epic Unfortunate - Junkrat Highlight',
'Epic Jailbird - Junkrat Skin',
'Epic Toasted - Junkrat Skin',
'LEGENDARY Jester - Junkrat Skin',
'LEGENDARY Fool - Junkrat Skin',
'LEGENDARY Hayseed - Junkrat Skin',
'LEGENDARY Scarecrow - Junkrat Skin',
'Normal Ahhhh! - Junkrat Spray',
'Normal Bang Bang - Junkrat Spray',
'Normal Crazy - Junkrat Spray',
'Normal Fireball - Junkrat Spray',
'Normal Firework - Junkrat Spray',
'Normal For You - Junkrat Spray',
'Normal Frag - Junkrat Spray',
'Normal Fuse - Junkrat Spray',
'Normal Grin - Junkrat Spray',
'Normal Icon - Junkrat Spray',
'Normal Junk - Junkrat Spray',
'Normal Kaboom! - Junkrat Spray',
'Normal Mad - Junkrat Spray',
'Normal Mayhem - Junkrat Spray',
'Normal Mine - Junkrat Spray',
'Normal Minefield - Junkrat Spray',
'Normal Smile - Junkrat Spray',
'Normal Smoke - Junkrat Spray',
'Normal Spin - Junkrat Spray',
'Normal Trapper - Junkrat Spray',
'Normal Wanted - Junkrat Spray',
'Normal Vroom! - Junkrat Spray',
'Normal Blow It Up Again - Junkrat Voice Line',
'Normal Anyone Want Some BBQ? - Junkrat Voice Line',
'Normal Brrring! - Junkrat Voice Line',
'Normal Coming Up Explodey! - Junkrat Voice Line',
'Normal Happy Birthday! - Junkrat Voice Line',
'Normal Have A Nice Day! - Junkrat Voice Line',
'Normal Its The Little Things - Junkrat Voice Line',
'Normal Kaboom - Junkrat Voice Line',
'Normal Ooh Shiny - Junkrat Voice Line',
'Normal Smile! - Junkrat Voice Line',
'Rare Itll Freeze That Way - Junkrat Pose',
'Rare Kneeling - Junkrat Pose',
'Rare Nyah Nyah - Junkrat Pose',
'Rare Bleached - Junkrat Skin',
'Rare Drowned - Junkrat Skin',
'Rare Irradiated - Junkrat Skin',
'Rare Rusted - Junkrat Skin',
'Epic Capoeira - Lucio Emote',
'Epic In The Groove - Lucio Emote',
'Epic Nah! - Lucio Emote',
'Epic Drop The Beat - Lucio Highlight',
'Epic Freestyle - Lucio Highlight',
'Epic In The Groove - Lucio Highlight',
'Epic Auditva - Lucio Skin',
'Epic Synaesthesia - Lucio Skin',
'LEGENDARY Hippityhop - Lucio Skin',
'LEGENDARY Ribbit - Lucio Skin',
'LEGENDARY Breakaway - Lucio Skin',
'LEGENDARY Slapshot - Lucio Skin',
'Normal Acelerar - Lucio Spray',
'Normal Baixo - Lucio Spray',
'Normal Bass - Lucio Spray',
'Normal Break It Down - Lucio Spray',
'Normal Cereal - Lucio Spray',
'Normal Confident - Lucio Spray',
'Normal Deck - Lucio Spray',
'Normal Frog - Lucio Spray',
'Normal Grin - Lucio Spray',
'Normal Hero - Lucio Spray',
'Normal Icon - Lucio Spray',
'Normal In Concert - Lucio Spray',
'Normal Kambo - Lucio Spray',
'Normal Scratch - Lucio Spray',
'Normal Signature - Lucio Spray',
'Normal Signature (2) - Lucio Spray',
'Normal Spin - Lucio Spray',
'Normal Tag - Lucio Spray',
'Normal Triplo - Lucio Spray',
'Normal Under Control - Lucio Spray',
'Normal Walk Of Fame - Lucio Spray',
'Normal Wave - Lucio Spray',
'Normal Cant Stop Wont Stop - Lucio Voice Line',
'Normal Hit Me! - Lucio Voice Line',
'Normal Im On Top Of The World - Lucio Voice Line',
'Normal I Could Do This All Day - Lucio Voice Line',
'Normal Jackpot! - Lucio Voice Line',
'Normal Not Hearing That Noise - Lucio Voice Line',
'Normal Oh Yeah! - Lucio Voice Line',
'Normal Tinnitus - Lucio Voice Line',
'Normal Why Are You So Angry? - Lucio Voice Line',
'Normal You Gotta Believe! - Lucio Voice Line',
'Rare Confident - Lucio Pose',
'Rare Grooving - Lucio Pose',
'Rare Ready for Action - Lucio Pose',
'Rare Azul - Lucio Skin',
'Rare Laranja - Lucio Skin',
'Rare Vermelho - Lucio Skin',
'Rare Roxo - Lucio Skin',
'Epic Gunspinning - McCree Emote',
'Epic Hat Tip - McCree Emote',
'Epic Spit - McCree Emote',
'Epic Rolling Into Action - McCree Highlight',
'Epic The Duel - McCree Highlight',
'Epic The Names McCree - McCree Highlight',
'Epic On The Range - McCree Skin',
'Epic White Hat - McCree Skin',
'LEGENDARY Gambler - McCree Skin',
'LEGENDARY Mystery Man - McCree Skin',
'LEGENDARY RiverBoat - McCree Skin',
'LEGENDARY Vigilante - McCree Skin',
'Normal Badge - McCree Spray',
'Normal BAMF - McCree Spray',
'Normal Bang! - McCree Spray',
'Normal Buckle - McCree Spray',
'Normal Bullet - McCree Spray',
'Normal Deadeye - McCree Spray',
'Normal Draw - McCree Spray',
'Normal Enigma - McCree Spray',
'Normal Gunslinger - McCree Spray',
'Normal High Noon - McCree Spray',
'Normal Icon - McCree Spray',
'Normal Jesse - McCree Spray',
'Normal Noose - McCree Spray',
'Normal Outlaw - McCree Spray',
'Normal Skull - McCree Spray',
'Normal Spin - McCree Spray',
'Normal Take It Easy - McCree Spray',
'Normal Target - McCree Spray',
'Normal The Names - McCree Spray',
'Normal Thumbs Up - McCree Spray',
'Normal Tumbleweed - McCree Spray',
'Normal Wanted - McCree Spray',
'Normal Your Face Here - McCree Spray',
'Normal Aint I Killed You Before - McCree Voice Line',
'Normal Happens To The Best Of Us - McCree Voice Line',
'Normal Im The Quick - McCree Voice Line',
'Normal Ive Got ABullet - McCree Voice Line',
'Normal I Tried Being Reasonable - McCree Voice Line',
'Normal Reach For The Sky - McCree Voice Line',
'Normal Sure As Hell Aint Ugly - McCree Voice Line',
'Normal Wanted: Dead Or Alive - McCree Voice Line',
'Normal You Done? - McCree Voice Line',
'Rare Contemplative - McCree Pose',
'Rare Over the Shoulder - McCree Pose',
'Rare Take it Easy - McCree Pose',
'Rare Ebony - McCree Skin',
'Rare Sage - McCree Skin',
'Rare Lake - McCree Skin',
'Rare Wheat - McCree Skin',
'Epic Companion - Mei Emote',
'Epic Spray - Mei Emote',
'Epic Yaaaaaaaaaaay! - Mei Emote',
'Epic Frosty :) - Mei Highlight',
'Epic Going Up! - Mei Highlight',
'Epic Skating Around - Mei Highlight',
'Epic Earthen - Mei Skin',
'Epic Snow Plum - Mei Skin',
'LEGENDARY Firefighter - Mei Skin',
'LEGENDARY Rescue Mei - Mei Skin',
'LEGENDARY Abominable - Mei Skin',
'LEGENDARY Yeti Hunter - Mei Skin',
'Normal ^_^ - Mei Spray',
'Normal >_< - Mei Spray',
'Normal Beat The Heat - Mei Spray',
'Normal Blaster - Mei Spray',
'Normal Carefree - Mei Spray',
'Normal Casual - Mei Spray',
'Normal Confident - Mei Spray',
'Normal Dizzy - Mei Spray',
'Normal Explorer - Mei Spray',
'Normal Eyes - Mei Spray',
'Normal Hairpin - Mei Spray',
'Normal Icon - Mei Spray',
'Normal Meis Journal - Mei Spray',
'Normal Popsicle - Mei Spray',
'Normal Print - Mei Spray',
'Normal Reading - Mei Spray',
'Normal Sketch - Mei Spray',
'Normal Smile - Mei Spray',
'Normal Snow Art - Mei Spray',
'Normal Snowball - Mei Spray',
'Normal Snowman - Mei Spray',
'Normal Soft Serve - Mei Spray',
'Normal Walled - Mei Spray',
'Normal A-Mei-Zing!- Mei Voice Line',
'Normal Chill Out! - Mei Voice Line',
'Normal Learned Your Lesson - Mei Voice Line',
'Normal Okay! - Mei Voice Line',
'Normal Ouch Are You Okay? - Mei Voice Line',
'Normal Sorry Sorry Sorry Sorry - Mei Voice Line',
'Normal That Was Great - Mei Voice Line',
'Normal Yay! - Mei Voice Line',
'Normal You Have To Let It Go - Mei Voice Line',
'Rare Casual - Mei Pose',
'Rare Hands on Hips - Mei Pose',
'Rare Kneeling - Mei Pose',
'Rare Jade - Mei Skin',
'Rare Persimmon - Mei Skin',
'Rare Heliotrope - Mei Skin',
'Rare Chrysanthemum - Mei Skin',
'Epic Applause - Mercy Emote',
'Epic Caduceus - Mercy Emote',
'Epic No Pulse - Mercy Emote',
'Epic Battle Angel - Mercy Highlight',
'Epic Guardian Angel - Mercy Highlight',
'Epic Heroes Never Die - Mercy Highlight',
'Epic Amber - Mercy Skin',
'Epic Cobalt - Mercy Skin',
'LEGENDARY Sigrun - Mercy Skin',
'LEGENDARY Valkyrie - Mercy Skin',
'LEGENDARY Devil - Mercy Skin',
'LEGENDARY Imp - Mercy Skin',
'Normal Arrow - Mercy Spray',
'Normal Bandage - Mercy Spray',
'Normal Battle Ready - Mercy Spray',
'Normal Blaster - Mercy Spray',
'Normal Emblem - Mercy Spray',
'Normal Gauze - Mercy Spray',
'Normal Halo - Mercy Spray',
'Normal Heroes Never Die - Mercy Spray',
'Normal Huge Rez!! - Mercy Spray',
'Normal Icon - Mercy Spray',
'Normal Light - Mercy Spray',
'Normal Medic - Mercy Spray',
'Normal On Call - Mercy Spray',
'Normal Patched Up - Mercy Spray',
'Normal Resurrect - Mercy Spray',
'Normal Smile - Mercy Spray',
'Normal Stethoscope - Mercy Spray',
'Normal Sting - Mercy Spray',
'Normal Support - Mercy Spray',
'Normal Swiss - Mercy Spray',
'Normal Valkyrie - Mercy Spray',
'Normal Wings - Mercy Spray',
'Normal Ziegler - Mercy Spray',
'Normal Consultation Fee - Mercy Voice Line',
'Normal Doctors Orders - Mercy Voice Line',
'Normal How Barbaric - Mercy Voice Line',
'Normal Miracle Worker - Mercy Voice Line',
'Normal Need A Second Opinion - Mercy Voice Line',
'Normal On A Scale Of 1-10- Mercy Voice Line',
'Normal Super! - Mercy Voice Line',
'Normal Take Two - Mercy Voice Line',
'Normal The Doctor Is In - Mercy Voice Line',
'Normal The Doctor Will See You - Mercy Voice Line',
'Rare Angelic - Mercy Pose',
'Rare Carefree - Mercy Pose',
'Rare Ready for Battle - Mercy Pose',
'Rare Celestial - Mercy Skin',
'Rare Mist - Mercy Skin',
'Rare Orchid - Mercy Skin',
'Rare Vendant - Mercy Skin',
'Epic Cheer - Pharah Emote',
'Epic Flourish - Pharah Emote',
'Epic Knuckles - Pharah Emote',
'Epic Barrage - Pharah Highlight',
'Epic Mission Complete - Pharah Highlight',
'Epic Touchdown - Pharah Highlight',
'Epic Anubis - Pharah Skin',
'Epic Jackal - Pharah Skin',
'LEGENDARY Mechaqueen - Pharah Skin',
'LEGENDARY Raptorion - Pharah Skin',
'LEGENDARY Raindancer - Pharah Skin',
'LEGENDARY Thunderbird - Pharah Skin',
'Normal Aerial Superiority - Pharah Spray',
'Normal Amari - Pharah Spray',
'Normal Ana - Pharah Spray',
'Normal Cobra - Pharah Spray',
'Normal Concussive Blast - Pharah Spray',
'Normal Guardian - Pharah Spray',
'Normal Hieroglyph - Pharah Spray',
'Normal Justice... - Pharah Spray',
'Normal On Guard - Pharah Spray',
'Normal Play Pharah - Pharah Spray',
'Normal Raptora - Pharah Spray',
'Normal Rocket Jump - Pharah Spray',
'Normal Rocket Launcher - Pharah Spray',
'Normal Salute - Pharah Spray',
'Normal Scarab - Pharah Spray',
'Normal Statue - Pharah Spray',
'Normal Stone - Pharah Spray',
'Normal Tattoo - Pharah Spray',
'Normal Wedjat - Pharah Spray',
'Normal Wings - Pharah Spray',
'Normal Wrist Launcher - Pharah Spray',
'Normal Aerial Superiority Achieved - Pharah Voice Line',
'Normal Flying Like An Egyptian - Pharah Voice Line',
'Normal Flying The Friendly Skies - Pharah Voice Line',
'Normal Got You On My Radar - Pharah Voice Line',
'Normal Leave This To A Professional - Pharah Voice Line',
'Normal Not A Chance - Pharah Voice Line',
'Normal Play Nice Play Pharah - Pharah Voice Line',
'Normal Rocket Jump? - Pharah Voice Line',
'Normal Shot Down - Pharah Voice Line',
'Normal Sorry But I Need To Jet - Pharah Voice Line',
'Rare Guardian - Pharah Pose',
'Rare Jump Jet - Pharah Pose',
'Rare Kneeling - Pharah Pose',
'Rare Amethyst - Pharah Skin',
'Rare Copper - Pharah Skin',
'Rare Emerald - Pharah Skin',
'Rare Titanium - Pharah Skin',
'Epic Not Impressed - Reaper Emote',
'Epic Slice - Reaper Emote',
'Epic Slow Clap - Reaper Emote',
'Epic Death Blossom - Reaper Highlight',
'Epic Executioner - Reaper Highlight',
'Epic Shadow Step - Reaper Highlight',
'Epic Desert - Reaper Skin',
'Epic Wight - Reaper Skin',
'LEGENDARY Plague Doctor - Reaper Skin',
'LEGENDARY El Blanco - Reaper Skin',
'LEGENDARY Mariachi - Reaper Skin',
'LEGENDARY Nevermore - Reaper Skin',
'Normal Blackwatch - Reaper Spray',
'Normal Blossom - Reaper Spray',
'Normal Cloaked - Reaper Spray',
'Normal Death Blossom - Reaper Spray',
'Normal Death Comes - Reaper Spray',
'Normal Die Die Die - Reaper Spray',
'Normal Everywhere - Reaper Spray',
'Normal Grave - Reaper Spray',
'Normal Hellfire - Reaper Spray',
'Normal Hooded - Reaper Spray',
'Normal Horns - Reaper Spray',
'Normal Icon - Reaper Spray',
'Normal Oops - Reaper Spray',
'Normal Psst - Reaper Spray',
'Normal Reap On - Reaper Spray',
'Normal Reaping - Reaper Spray',
'Normal Revenge - Reaper Spray',
'Normal Scythes - Reaper Spray',
'Normal Shadow - Reaper Spray',
'Normal Shadow Step - Reaper Spray',
'Normal Silent - Reaper Spray',
'Normal Soul Globe - Reaper Spray',
'Normal Time To Kill - Reaper Spray',
'Normal Dead Man Walking - Reaper Voice Line',
'Normal Give Me A Break - Reaper Voice Line',
'Normal Havent I Killed You - Reaper Voice Line',
'Normal Im Back In Black - Reaper Voice Line',
'Normal If It Lives I Can Kill It - Reaper Voice Line',
'Normal Next - Reaper Voice Line',
'Normal Psychopath - Reaper Voice Line',
'Normal Seen A Ghost? - Reaper Voice Line',
'Normal Too Easy - Reaper Voice Line',
'Normal Was That All? - Reaper Voice Line',
'Rare Casual - Reaper Pose',
'Rare Enigmatic - Reaper Pose',
'Rare Menacing - Reaper Pose',
'Rare Blood - Reaper Skin',
'Rare Midnight - Reaper Skin',
'Rare Moss - Reaper Skin',
'Rare Royal - Reaper Skin',
'Epic Flex - Reinhardt Emote',
'Epic Taunt - Reinhardt Emote',
'Epic Warriors Salute - Reinhardt Emote',
'Epic Charge - Reinhardt Highlight',
'Epic Hammer Down - Reinhardt Highlight',
'Epic More Stretching Required - Reinhardt Highlight',
'Epic Bundeswehr - Reinhardt Skin',
'Epic Paragon - Reinhardt Skin',
'LEGENDARY Blackhardt - Reinhardt Skin',
'LEGENDARY Bloodhardt - Reinhardt Skin',
'LEGENDARY Lionhardt - Reinhardt Skin',
'LEGENDARY Stonehardt - Reinhardt Skin',
'Normal Barrier - Reinhardt Spray',
'Normal Charge - Reinhardt Spray',
'Normal Cracks - Reinhardt Spray',
'Normal Crusader - Reinhardt Spray',
'Normal Earthshatter - Reinhardt Spray',
'Normal Emblem - Reinhardt Spray',
'Normal Fire Strike - Reinhardt Spray',
'Normal Glorious - Reinhardt Spray',
'Normal Hammer Down - Reinhardt Spray',
'Normal Helm - Reinhardt Spray',
'Normal Honor - Reinhardt Spray',
'Normal Icon - Reinhardt Spray',
'Normal Knight - Reinhardt Spray',
'Normal Lion - Reinhardt Spray',
'Normal Roar - Reinhardt Spray',
'Normal Royal - Reinhardt Spray',
'Normal Shield Up - Reinhardt Spray',
'Normal Stein - Reinhardt Spray',
'Normal Swing - Reinhardt Spray',
'Normal Vigilant - Reinhardt Spray',
'Normal White - Reinhardt Spray',
'Normal Wilhelm - Reinhardt Spray',
'Normal Wrestle - Reinhardt Spray',
'Normal Are You Afraid? - Reinhardt Voice Line',
'Normal Bring Me Another - Reinhardt Voice Line',
'Normal Catch Phrase! - Reinhardt Voice Line',
'Normal Crusader Online - Reinhardt Voice Line',
'Normal Crushing Machine - Reinhardt Voice Line',
'Normal German Engineering - Reinhardt Voice Line',
'Normal Honor And Glory - Reinhardt Voice Line',
'Normal Respect Your Elders - Reinhardt Voice Line',
'Normal Show You How Its Done - Reinhardt Voice Line',
'Normal This Old Dog - Reinhardt Voice Line',
'Rare Confident - Reinhardt Pose',
'Rare Flex - Reinhardt Pose',
'Rare Legendary - Reinhardt Pose',
'Rare Brass - Reinhardt Skin',
'Rare Cobalt - Reinhardt Skin',
'Rare Copper - Reinhardt Skin',
'Rare Viridian - Reinhardt Skin',
'Epic Boo! - Roadhog Emote',
'Epic Can Crusher - Roadhog Emote',
'Epic Headbanging - Roadhog Emote',
'Epic Little Piggy - Roadhog Highlight',
'Epic Say Cheese - Roadhog Highlight',
'Epic Whole Hog - Roadhog Highlight',
'Epic Pigpen - Roadhog Skin',
'Epic Stitched - Roadhog Skin',
'LEGENDARY Mako - Roadhog Skin',
'LEGENDARY Toa - Roadhog Skin',
'LEGENDARY Islander - Roadhog Skin',
'LEGENDARY Sharkbait - Roadhog Skin',
'Normal Breathin - Roadhog Spray',
'Normal Deep Thoughts - Roadhog Spray',
'Normal Emblem - Roadhog Spray',
'Normal Eyes - Roadhog Spray',
'Normal Free Pig - Roadhog Spray',
'Normal Fresh Meat - Roadhog Spray',
'Normal Gotcha - Roadhog Spray',
'Normal Grand Theft - Roadhog Spray',
'Normal Helmet - Roadhog Spray',
'Normal Here Piggy - Roadhog Spray',
'Normal Hogpower - Roadhog Spray',
'Normal Hooked - Roadhog Spray',
'Normal Icon - Roadhog Spray',
'Normal Left - Roadhog Spray',
'Normal License - Roadhog Spray',
'Normal Mako - Roadhog Spray',
'Normal No Pork - Roadhog Spray',
'Normal Piggy - Roadhog Spray',
'Normal Popper - Roadhog Spray',
'Normal Tails - Roadhog Spray',
'Normal Toxic - Roadhog Spray',
'Normal Wanted - Roadhog Spray',
'Normal Wild Hog - Roadhog Spray',
'Normal Candy From A Baby - Roadhog Voice Line',
'Normal Got Something To Say? - Roadhog Voice Line',
'Normal Hahaha! - Roadhog Voice Line',
'Normal Hook Line and Sinker - Roadhog Voice Line',
'Normal Life is Pain So Is Death - Roadhog Voice Line',
'Normal Piece Of Cake - Roadhog Voice Line',
'Normal Push Off - Roadhog Voice Line',
'Normal Say Bacon... - Roadhog Voice Line',
'Normal Violence Is The Answer - Roadhog Voice Line',
'Normal Were All Animals - Roadhog Voice Line',
'Rare Pointing to the Sky - Roadhog Pose',
'Rare Thumbs Up - Roadhog Pose',
'Rare Tuckered Out - Roadhog Pose',
'Rare Kiwi - Roadhog Skin',
'Rare Mud - Roadhog Skin',
'Rare Thistle - Roadhog Skin',
'Rare Sand - Roadhog Skin',
'Epic Fist - Soldier: 76 Emote',
'Epic I See You - Soldier: 76 Emote',
'Epic Locked And Loaded - Soldier: 76 Emote',
'Epic Helix - Soldier: 76 Highlight',
'Epic Looking At You - Soldier: 76 Highlight',
'Epic Target Rich Environment - Soldier: 76 Highlight',
'Epic Bone - Soldier: 76 Skin',
'Epic Golden - Soldier: 76 Skin',
'LEGENDARY Commando - Soldier: 76 Skin',
'LEGENDARY Night Ops - Soldier: 76 Skin',
'LEGENDARY Daredevil - Soldier: 76 Skin',
'LEGENDARY Stunt Rider - Soldier: 76 Skin',
'Normal 76- Soldier: 76 Spray',
'Normal All Soldiers - Soldier: 76 Spray',
'Normal American Hero - Soldier: 76 Spray',
'Normal Coin - Soldier: 76 Spray',
'Normal Grave - Soldier: 76 Spray',
'Normal Grizzled - Soldier: 76 Spray',
'Normal Heal Up - Soldier: 76 Spray',
'Normal Helix - Soldier: 76 Spray',
'Normal Hooah - Soldier: 76 Spray',
'Normal Icon - Soldier: 76 Spray',
'Normal Jacket: 76 - Soldier: 76 Spray',
'Normal Move! - Soldier: 76 Spray',
'Normal Muzzle - Soldier: 76 Spray',
'Normal Old Soldier - Soldier: 76 Spray',
'Normal Pulse Rifle - Soldier: 76 Spray',
'Normal Rifle: 76 - Soldier: 76 Spray',
'Normal Rockets - Soldier: 76 Spray',
'Normal Salute - Soldier: 76 Spray',
'Normal Strike Commander - Soldier: 76 Spray',
'Normal Vigilante - Soldier: 76 Spray',
'Normal Vigilante (2) - Soldier: 76 Spray',
'Normal Visor - Soldier: 76 Spray',
'Normal Wanted - Soldier: 76 Spray',
'Normal Get Off My Lawn - Soldier: 76 Voice Line',
'Normal Im An Army Of One - Soldier: 76 Voice Line',
'Normal I Didnt Start This War... - Soldier: 76 Voice Line',
'Normal Not On My Watch - Soldier: 76 Voice Line',
'Normal Old Soldiers - Soldier: 76 Voice Line',
'Normal Smells Like Victory - Soldier: 76 Voice Line',
'Normal Thats Sir To You - Soldier: 76 Voice Line',
'Normal What Are You Lookin At? - Soldier: 76 Voice Line',
'Normal Youre The Other One - Soldier: 76 Voice Line',
'Normal You Didnt Make The Cut - Soldier: 76 Voice Line',
'Rare Fist Pump - Soldier: 76 Pose',
'Rare Locked and Loaded - Soldier: 76 Pose',
'Rare Soldier - Soldier: 76 Pose',
'Rare Olive - Soldier: 76 Skin',
'Rare Russet - Soldier: 76 Skin',
'Rare Jet - Soldier: 76 Skin',
'Rare Smoke - Soldier: 76 Skin',
'Normal ...Punch - Spray ',
'Normal Catcher - Spray ',
'Normal Caution - Spray ',
'Normal Dance - Spray ',
'Normal Dark Overwatch - Spray ',
'Normal Dark Title - Spray ',
'Normal FOTS2 - Spray ',
'Normal Fuji - Spray ',
'Normal Goldshire Pictures - Spray ',
'Normal Leek - Spray ',
'Normal Lumerico - Spray ',
'Normal Numbani Statue - Spray ',
'Normal Omnic Rights - Spray ',
'Normal Overwatch - Spray ',
'Normal Overwatch Title - Spray ',
'Normal Rhino - Spray ',
'Normal Rikimaru - Spray ',
'Normal Sarcophagus - Spray ',
'Normal Scooter - Spray ',
'Normal Scroll - Spray ',
'Normal Siege Mode - Spray ',
'Normal Six-Gun Killer- Spray ',
'Normal Sol - Spray ',
'Normal Soulstone - Spray ',
'Normal Vives Adventure - Spray ',
'Epic Clap - Symmetra Emote',
'Epic Flow - Symmetra Emote',
'Epic Insignificant - Symmetra Emote',
'Epic Askew - Symmetra Highlight',
'Epic Dance - Symmetra Highlight',
'Epic My Reality - Symmetra Highlight',
'Epic Regal - Symmetra Skin',
'Epic Utopaea - Symmetra Skin',
'LEGENDARY Architech - Symmetra Skin',
'LEGENDARY Devi - Symmetra Skin',
'LEGENDARY Goddess - Symmetra Skin',
'LEGENDARY Vishkar - Symmetra Skin',
'Normal Agent - Symmetra Spray',
'Normal Architect - Symmetra Spray',
'Normal Behold - Symmetra Spray',
'Normal Blueprint - Symmetra Spray',
'Normal Builder - Symmetra Spray',
'Normal Car Wash - Symmetra Spray',
'Normal Caution - Symmetra Spray',
'Normal Design - Symmetra Spray',
'Normal Glove - Symmetra Spray',
'Normal Icon - Symmetra Spray',
'Normal Light - Symmetra Spray',
'Normal Lines - Symmetra Spray',
'Normal Lotus - Symmetra Spray',
'Normal Pose - Symmetra Spray',
'Normal Projector - Symmetra Spray',
'Normal Satya - Symmetra Spray',
'Normal Superior - Symmetra Spray',
'Normal The Path - Symmetra Spray',
'Normal Vaswani - Symmetra Spray',
'Normal Vishkar - Symmetra Spray',
'Normal Visor - Symmetra Spray',
'Normal Weaver - Symmetra Spray',
'Normal Will - Symmetra Spray',
'Normal How Unsightly - Symmetra Voice Line',
'Normal Everything By Design - Symmetra Voice Line',
'Normal Exquisite - Symmetra Voice Line',
'Normal I Dont Think So - Symmetra Voice Line',
'Normal Impressive - Symmetra Voice Line',
'Normal Perfect Harmony - Symmetra Voice Line',
'Normal Precisely - Symmetra Voice Line',
'Normal Put You In Your Place - Symmetra Voice Line',
'Normal Welcome To My Reality - Symmetra Voice Line',
'Normal Why Do You Struggle? - Symmetra Voice Line',
'Rare Balance - Symmetra Pose',
'Rare Creation - Symmetra Pose',
'Rare Dance - Symmetra Pose',
'Rare Hyacinth - Symmetra Skin',
'Rare Cardamom - Symmetra Skin',
'Rare Saffron - Symmetra Skin',
'Rare Technomancer - Symmetra Skin',
'Epic Clicking Heels - Torbjorn Emote',
'Epic Fisticuffs - Torbjorn Emote',
'Epic Overload - Torbjorn Emote',
'Epic In Your Face - Torbjorn Highlight',
'Epic Refreshing - Torbjorn Highlight',
'Epic Ride Em - Torbjorn Highlight',
'Epic Cathode - Torbjorn Skin',
'Epic Woodclad - Torbjorn Skin',
'LEGENDARY Barbarossa - Torbjorn Skin',
'LEGENDARY Blackbeard - Torbjorn Skin',
'LEGENDARY Chopper - Torbjorn Skin',
'LEGENDARY Deadlock - Torbjorn Skin',
'Normal Armor - Torbjorn Spray',
'Normal Beard - Torbjorn Spray',
'Normal Catch A Ride - Torbjorn Spray',
'Normal Chef - Torbjorn Spray',
'Normal Claw - Torbjorn Spray',
'Normal Fix It Up - Torbjorn Spray',
'Normal Forged - Torbjorn Spray',
'Normal Gears - Torbjorn Spray',
'Normal Get Ready - Torbjorn Spray',
'Normal Hammer - Torbjorn Spray',
'Normal Hot - Torbjorn Spray',
'Normal Icon - Torbjorn Spray',
'Normal Ironclad - Torbjorn Spray',
'Normal Kanon - Torbjorn Spray',
'Normal Mask - Torbjorn Spray',
'Normal Molten Core - Torbjorn Spray',
'Normal Ready To Work - Torbjorn Spray',
'Normal Run! - Torbjorn Spray',
'Normal Smalt - Torbjorn Spray',
'Normal Stoic - Torbjorn Spray',
'Normal Turret - Torbjorn Spray',
'Normal Turrets - Torbjorn Spray',
'Normal Upgradera - Torbjorn Spray',
'Normal A Chicken Out Of A Feather - Torbjorn Voice Line',
'Normal Completion Date? - Torbjorn Voice Line',
'Normal Dont Get Caught - Torbjorn Voice Line',
'Normal Engineers - Torbjorn Voice Line',
'Normal Im Giving It All Ive Got! - Torbjorn Voice Line',
'Normal Im Swedish - Torbjorn Voice Line',
'Normal Leave This To An Expert - Torbjorn Voice Line',
'Normal Lets Not Buy The Pig - Torbjorn Voice Line',
'Normal Some Assembly Required - Torbjorn Voice Line',
'Normal Working As Intended - Torbjorn Voice Line',
'Rare Hammer - Torbjorn Pose',
'Rare Sitting Pretty - Torbjorn Pose',
'Rare Take Five - Torbjorn Pose',
'Rare Bla - Torbjorn Skin',
'Rare Citron - Torbjorn Skin',
'Rare Gron - Torbjorn Skin',
'Rare Plommon - Torbjorn Skin',
'Epic Cheer - Tracer Emote',
'Epic Laughing - Tracer Emote',
'Epic Spin - Tracer Emote',
'Epic Backflip - Tracer Highlight',
'Epic Just In Time - Tracer Highlight',
'Epic Serious Business - Tracer Highlight',
'Epic Posh - Tracer Skin',
'Epic Sporty - Tracer Skin',
'LEGENDARY T. Racer - Tracer Skin',
'LEGENDARY Mach T - Tracer Skin',
'LEGENDARY Punk - Tracer Skin',
'LEGENDARY Ultraviolet - Tracer Skin',
'Normal Blink - Tracer Spray',
'Normal Bombs Away! - Tracer Spray',
'Normal Calavarys Here - Tracer Spray',
'Normal Cheers - Tracer Spray',
'Normal Cheers Love - Tracer Spray',
'Normal Clocks Tickin - Tracer Spray',
'Normal Confident - Tracer Spray',
'Normal Fighter - Tracer Spray',
'Normal Icon - Tracer Spray',
'Normal Kneeling - Tracer Spray',
'Normal Lena - Tracer Spray',
'Normal Orange - Tracer Spray',
'Normal Pew! Pew! Pew! - Tracer Spray',
'Normal Pistols - Tracer Spray',
'Normal Portrait - Tracer Spray',
'Normal Poster - Tracer Spray',
'Normal Pulse Bomb - Tracer Spray',
'Normal Ready For Action - Tracer Spray',
'Normal Salute - Tracer Spray',
'Normal Shaded - Tracer Spray',
'Normal Tagged - Tracer Spray',
'Normal Whatcha Lookin At? - Tracer Spray',
'Normal Wings - Tracer Spray',
'Normal Aw Rubbish - Tracer Voice Line',
'Normal Be Right Back! - Tracer Voice Line',
'Normal Check Me Out - Tracer Voice Line',
'Normal Cheers Love! - Tracer Voice Line',
'Normal Deja Vu - Tracer Voice Line',
'Normal Keep Calm - Tracer Voice Line',
'Normal She Shoots She Scores - Tracer Voice Line',
'Normal The World Needs Heroes - Tracer Voice Line',
'Normal Under Control - Tracer Voice Line',
'Normal You Need A Time Out - Tracer Voice Line',
'Rare Over the Shoulder - Tracer Pose',
'Rare Salute - Tracer Pose',
'Rare Sitting - Tracer Pose',
'Rare Royal Blue - Tracer Skin',
'Rare Neon Green - Tracer Skin',
'Rare Hot Pink - Tracer Skin',
'Rare Electric Purple - Tracer Skin',
'Epic Curtain Call - Widowmaker Emote',
'Epic Shot Dead - Widowmaker Emote',
'Epic Widows Kiss - Widowmaker Emote',
'Epic Hanging Around - Widowmaker Highlight',
'Epic I See You... - Widowmaker Highlight',
'Epic Swinging Into Action - Widowmaker Highlight',
'Epic Winter - Widowmaker Skin',
'Epic Patina - Widowmaker Skin',
'LEGENDARY Odette - Widowmaker Skin',
'LEGENDARY Odile - Widowmaker Skin',
'LEGENDARY Comtesse - Widowmaker Skin',
'LEGENDARY Huntress - Widowmaker Skin',
'Normal Baiser - Widowmaker Spray',
'Normal Black Widow - Widowmaker Spray',
'Normal Blood - Widowmaker Spray',
'Normal Crouch - Widowmaker Spray',
'Normal Detected - Widowmaker Spray',
'Normal Emblem - Widowmaker Spray',
'Normal Gaze - Widowmaker Spray',
'Normal Hourglass - Widowmaker Spray',
'Normal Icon - Widowmaker Spray',
'Normal In My Sights - Widowmaker Spray',
'Normal Je Te Vois - Widowmaker Spray',
'Normal Kneeling - Widowmaker Spray',
'Normal No One Escapes - Widowmaker Spray',
'Normal Noire - Widowmaker Spray',
'Normal Portrait - Widowmaker Spray',
'Normal Scope - Widowmaker Spray',
'Normal Sniper - Widowmaker Spray',
'Normal Spider - Widowmaker Spray',
'Normal Swing - Widowmaker Spray',
'Normal Une Balle - Widowmaker Spray',
'Normal Veuve - Widowmaker Spray',
'Normal Widow - Widowmaker Spray',
'Normal Widows Kiss - Widowmaker Spray',
'Normal Encore? - Widowmaker Voice Line',
'Normal Let Them Eat Cake - Widowmaker Voice Line',
'Normal Look For The Woman - Widowmaker Voice Line',
'Normal Magnifique - Widowmaker Voice Line',
'Normal One Shot One Kill - Widowmaker Voice Line',
'Normal Ouh La La - Widowmaker Voice Line',
'Normal Step Into My Parlor - Widowmaker Voice Line',
'Normal Thats How It Is - Widowmaker Voice Line',
'Normal To Life To Death - Widowmaker Voice Line',
'Normal Whats An Aimbot - Widowmaker Voice Line',
'Rare Activating Visor - Widowmaker Pose',
'Rare Gaze - Widowmaker Pose',
'Rare Over the Shoulder - Widowmaker Pose',
'Rare Ciel - Widowmaker Skin',
'Rare Nuit - Widowmaker Skin',
'Rare Vert - Widowmaker Skin',
'Rare Rose - Widowmaker Skin',
'Epic Monkey Business - Winston Emote',
'Epic Peanut Butter? - Winston Emote',
'Epic Roar - Winston Emote',
'Epic Excuse Me - Winston Highlight',
'Epic Glasses - Winston Highlight',
'Epic Primal Rage - Winston Highlight',
'Epic Desert - Winston Skin',
'Epic Horizon - Winston Skin',
'LEGENDARY Explorer - Winston Skin',
'LEGENDARY Frogston - Winston Skin',
'LEGENDARY Undersea - Winston Skin',
'LEGENDARY Safari - Winston Skin',
'Normal Angry - Winston Spray',
'Normal Ape Crossing - Winston Spray',
'Normal Baby - Winston Spray',
'Normal Banana - Winston Spray',
'Normal Explorer - Winston Spray',
'Normal Fastball - Winston Spray',
'Normal Harold - Winston Spray',
'Normal Horizon - Winston Spray',
'Normal Icon - Winston Spray',
'Normal Lexigrams - Winston Spray',
'Normal Lightning - Winston Spray',
'Normal Mine! - Winston Spray',
'Normal PB - Winston Spray',
'Normal Primal Rage - Winston Spray',
'Normal Q.E.D. - Winston Spray',
'Normal Rage - Winston Spray',
'Normal Research - Winston Spray',
'Normal Roar - Winston Spray',
'Normal Science! - Winston Spray',
'Normal Swing - Winston Spray',
'Normal White - Winston Spray',
'Normal Wow - Winston Spray',
'Normal ...Excuse Me - Winston Voice Line',
'Normal Dont Get Me Angry - Winston Voice Line',
'Normal How Embarrasing - Winston Voice Line',
'Normal I Do Not Want A Banana - Winston Voice Line',
'Normal Natural Selection - Winston Voice Line',
'Normal No Monkey Business - Winston Voice Line',
'Normal Peanut Butter? - Winston Voice Line',
'Normal Sorry About That! - Winston Voice Line',
'Normal The Power Of Science! - Winston Voice Line',
'Normal We Have A Problem - Winston Voice Line',
'Rare Beast - Winston Pose',
'Rare Glasses - Winston Pose',
'Rare The Thinker - Winston Pose',
'Rare Banana - Winston Skin',
'Rare Forest - Winston Skin',
'Rare Red Planet - Winston Skin',
'Rare Atmosphere - Winston Skin',
'Epic Bring It On - Zarya Emote',
'Epic Crush You - Zarya Emote',
'Epic Pumping Iron - Zarya Emote',
'Epic Deadlift - Zarya Highlight',
'Epic Maximum Charge - Zarya Highlight',
'Epic This Is Strength - Zarya Highlight',
'Epic Dawn - Zarya Skin',
'Epic Midnight - Zarya Skin',
'LEGENDARY Arctic - Zarya Skin',
'LEGENDARY Siberian Front - Zarya Skin',
'LEGENDARY Cyber Goth - Zarya Skin',
'LEGENDARY Industrial - Zarya Skin',
'Normal 512- Zarya Spray',
'Normal Alexandra - Zarya Spray',
'Normal Avenger - Zarya Spray',
'Normal Avenger (2) - Zarya Spray',
'Normal Barrier - Zarya Spray',
'Normal Bear - Zarya Spray',
'Normal Cannon - Zarya Spray',
'Normal Champion - Zarya Spray',
'Normal Defender - Zarya Spray',
'Normal Focused - Zarya Spray',
'Normal Gun Show - Zarya Spray',
'Normal Icon - Zarya Spray',
'Normal Lift - Zarya Spray',
'Normal Pink - Zarya Spray',
'Normal Pumped - Zarya Spray',
'Normal Shield - Zarya Spray',
'Normal Smile - Zarya Spray',
'Normal Strength - Zarya Spray',
'Normal Surge - Zarya Spray',
'Normal Tobelstein - Zarya Spray',
'Normal We Are Strong - Zarya Spray',
'Normal Weights - Zarya Spray',
'Normal Wrestle - Zarya Spray',
'Normal Get Down Give Me 20 - Zarya Voice Line',
'Normal I Am Mother Russia - Zarya Voice Line',
'Normal I Can Bench More Than You - Zarya Voice Line',
'Normal I Will Break You - Zarya Voice Line',
'Normal Need Personal Training? - Zarya Voice Line',
'Normal No Mercy - Zarya Voice Line',
'Normal Siberian Bear - Zarya Voice Line',
'Normal Together We Are Strong - Zarya Voice Line',
'Normal Welcome To The Gun Show - Zarya Voice Line',
'Rare Casual - Zarya Pose',
'Rare Check Out This Gun - Zarya Pose',
'Rare Flexing - Zarya Pose',
'Rare Brick - Zarya Skin',
'Rare Taiga - Zarya Skin',
'Rare Violet - Zarya Skin',
'Rare Goldenrod - Zarya Skin',
'Epic Focusing - Zenyatta Emote',
'Epic Round Of Applause - Zenyatta Emote',
'Epic Taunt - Zenyatta Emote',
'Epic Focused - Zenyatta Highlight',
'Epic Harmony And Discord - Zenyatta Highlight',
'Epic Transcendence - Zenyatta Highlight',
'Epic Ascendant - Zenyatta Skin',
'Epic Harmonious - Zenyatta Skin',
'LEGENDARY Djinyatta - Zenyatta Skin',
'LEGENDARY Ifrit - Zenyatta Skin',
'LEGENDARY Ra - Zenyatta Skin',
'LEGENDARY Sunyatta - Zenyatta Skin',
'Normal Adorable - Zenyatta Spray',
'Normal Aura - Zenyatta Spray',
'Normal Balance - Zenyatta Spray',
'Normal Contemplative - Zenyatta Spray',
'Normal Discord - Zenyatta Spray',
'Normal Enlightened - Zenyatta Spray',
'Normal Fist Bump - Zenyatta Spray',
'Normal Flow - Zenyatta Spray',
'Normal Foot - Zenyatta Spray',
'Normal Graphic - Zenyatta Spray',
'Normal Guru - Zenyatta Spray',
'Normal Hand - Zenyatta Spray',
'Normal Harmony - Zenyatta Spray',
'Normal Icon - Zenyatta Spray',
'Normal Inner Fire - Zenyatta Spray',
'Normal Nine - Zenyatta Spray',
'Normal Orb - Zenyatta Spray',
'Normal Orbs - Zenyatta Spray',
'Normal Peace - Zenyatta Spray',
'Normal Taunt - Zenyatta Spray',
'Normal Tekhartha - Zenyatta Spray',
'Normal Throw - Zenyatta Spray',
'Normal Together - Zenyatta Spray',
'Normal Death Is Whimsical Today - Zenyatta Voice Line',
'Normal Do I Think? - Zenyatta Voice Line',
'Normal Free Your Mind - Zenyatta Voice Line',
'Normal Hello World! - Zenyatta Voice Line',
'Normal I Dreamt I Was A Butterfly - Zenyatta Voice Line',
'Normal I Think Therefor I am - Zenyatta Voice Line',
'Normal I Will Not Juggle - Zenyatta Voice Line',
'Normal Ones and Zeroes - Zenyatta Voice Line',
'Normal Peace And Blessings - Zenyatta Voice Line',
'Normal The Iris Embraces You - Zenyatta Voice Line',
'Rare Balance - Zenyatta Pose',
'Rare Harmony - Zenyatta Pose',
'Rare Peace - Zenyatta Pose',
'Rare Air - Zenyatta Skin',
'Rare Earth - Zenyatta Skin',
'Rare Leaf - Zenyatta Skin',
'Rare Water - Zenyatta Skin',
'Rare 50 Coins',
'Epic 150 Coins',
'LEGENDARY 500 Coins'
];
var weights = [
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
59,
32,
32,
32,
32,
32,
32,
32,
32,
7,
2,
];

var specloot = [
  'Epic Alert! Alert! - Bastion Emote',
'Epic Dizzy - Bastion Emote',
'Epic Robot - Bastion Emote',
'Epic Bullet Rain - Bastion Highlight',
'Epic Ganymede - Bastion Highlight',
'Epic On Guard - Bastion Highlight',
'Epic Omnic Crisis - Bastion Skin',
'Epic Defense Matrix- Bastion Skin',
'Epic Eject - D.Va Highlight',
'Epic Lying Around - D.Va Highlight',
'Epic Meka Activated - D.Va Highlight',
'Epic Carbon Fiber - D.Va Skin',
'Epic White Rabbit - D.Va Skin',
'Epic Challenge - Genji Emote',
'Epic Cutting Edge - Genji Emote',
'Epic Salute - Genji Emote',
'Epic Shuriken - Genji Highlight',
'Epic Unsheathing the Sword - Genji Highlight',
'Epic Warriors Salute - Genji Highlight',
'Epic Carbon Fiber - Genji Skin',
'Epic Chrome - Genji Skin',
'Epic Beckon - Hanzo Emote',
'Epic Brush Shoulder - Hanzo Emote',
'Epic Victory - Hanzo Emote',
'Epic Backflip - Hanzo Highlight',
'Epic My Aim is True - Hanzo Highlight',
'Epic Superior - Hanzo Highlight',
'Epic Cloud - Hanzo Skin',
'Epic Dragon - Hanzo Skin',
'Epic Juggling - Junkrat Emote',
'Epic Puppet - Junkrat Emote',
'Epic Vaudeville - Junkrat Emote',
'Epic Im Flying! - Junkrat Highlight',
'Epic Rip-Tire- Junkrat Highlight',
'Epic Unfortunate - Junkrat Highlight',
'Epic Jailbird - Junkrat Skin',
'Epic Toasted - Junkrat Skin',
'Epic Capoeira - Lucio Emote',
'Epic In The Groove - Lucio Emote',
'Epic Nah! - Lucio Emote',
'Epic Drop The Beat - Lucio Highlight',
'Epic Freestyle - Lucio Highlight',
'Epic In The Groove - Lucio Highlight',
'Epic Auditva - Lucio Skin',
'Epic Synaesthesia - Lucio Skin',
'Epic Gunspinning - McCree Emote',
'Epic Hat Tip - McCree Emote',
'Epic Spit - McCree Emote',
'Epic Rolling Into Action - McCree Highlight',
'Epic The Duel - McCree Highlight',
'Epic The Names McCree - McCree Highlight',
'Epic On The Range - McCree Skin',
'Epic White Hat - McCree Skin',
'Epic Companion - Mei Emote',
'Epic Spray - Mei Emote',
'Epic Yaaaaaaaaaaay! - Mei Emote',
'Epic Frosty :) - Mei Highlight',
'Epic Going Up! - Mei Highlight',
'Epic Skating Around - Mei Highlight',
'Epic Earthen - Mei Skin',
'Epic Snow Plum - Mei Skin',
'Epic Applause - Mercy Emote',
'Epic Caduceus - Mercy Emote',
'Epic No Pulse - Mercy Emote',
'Epic Battle Angel - Mercy Highlight',
'Epic Guardian Angel - Mercy Highlight',
'Epic Heroes Never Die - Mercy Highlight',
'Epic Amber - Mercy Skin',
'Epic Cobalt - Mercy Skin',
'Epic Cheer - Pharah Emote',
'Epic Flourish - Pharah Emote',
'Epic Knuckles - Pharah Emote',
'Epic Barrage - Pharah Highlight',
'Epic Mission Complete - Pharah Highlight',
'Epic Touchdown - Pharah Highlight',
'Epic Anubis - Pharah Skin',
'Epic Jackal - Pharah Skin',
'Epic Not Impressed - Reaper Emote',
'Epic Slice - Reaper Emote',
'Epic Slow Clap - Reaper Emote',
'Epic Death Blossom - Reaper Highlight',
'Epic Executioner - Reaper Highlight',
'Epic Shadow Step - Reaper Highlight',
'Epic Desert - Reaper Skin',
'Epic Wight - Reaper Skin',
'Epic Flex - Reinhardt Emote',
'Epic Taunt - Reinhardt Emote',
'Epic Warriors Salute - Reinhardt Emote',
'Epic Charge - Reinhardt Highlight',
'Epic Hammer Down - Reinhardt Highlight',
'Epic More Stretching Required - Reinhardt Highlight',
'Epic Bundeswehr - Reinhardt Skin',
'Epic Paragon - Reinhardt Skin',
'Epic Boo! - Roadhog Emote',
'Epic Can Crusher - Roadhog Emote',
'Epic Headbanging - Roadhog Emote',
'Epic Little Piggy - Roadhog Highlight',
'Epic Say "Cheese" - Roadhog Highlight',
'Epic Whole Hog - Roadhog Highlight',
'Epic Pigpen - Roadhog Skin',
'Epic Stitched - Roadhog Skin',
'Epic Fist - Soldier: 76 Emote',
'Epic I See You - Soldier: 76 Emote',
'Epic Locked And Loaded - Soldier: 76 Emote',
'Epic Helix - Soldier: 76 Highlight',
'Epic Looking At You - Soldier: 76 Highlight',
'Epic Target Rich Environment - Soldier: 76 Highlight',
'Epic Bone - Soldier: 76 Skin',
'Epic Golden - Soldier: 76 Skin',
'Epic Clap - Symmetra Emote',
'Epic Flow - Symmetra Emote',
'Epic Insignificant - Symmetra Emote',
'Epic Askew - Symmetra Highlight',
'Epic Dance - Symmetra Highlight',
'Epic My Reality - Symmetra Highlight',
'Epic Regal - Symmetra Skin',
'Epic Utopaea - Symmetra Skin',
'Epic Clicking Heels - Torbjorn Emote',
'Epic Fisticuffs - Torbjorn Emote',
'Epic Overload - Torbjorn Emote',
'Epic In Your Face - Torbjorn Highlight',
'Epic Refreshing - Torbjorn Highlight',
'Epic Ride Em - Torbjorn Highlight',
'Epic Cathode - Torbjorn Skin',
'Epic Woodclad - Torbjorn Skin',
'Epic Cheer - Tracer Emote',
'Epic Laughing - Tracer Emote',
'Epic Spin - Tracer Emote',
'Epic Backflip - Tracer Highlight',
'Epic Just In Time - Tracer Highlight',
'Epic Serious Business - Tracer Highlight',
'Epic Posh - Tracer Skin',
'Epic Sporty - Tracer Skin',
'Epic Curtain Call - Widowmaker Emote',
'Epic Shot Dead - Widowmaker Emote',
'Epic Widows Kiss - Widowmaker Emote',
'Epic Hanging Around - Widowmaker Highlight',
'Epic I See You... - Widowmaker Highlight',
'Epic Swinging Into Action - Widowmaker Highlight',
'Epic Winter - Widowmaker Skin',
'Epic Patina - Widowmaker Skin',
'Epic Monkey Business - Winston Emote',
'Epic Peanut Butter? - Winston Emote',
'Epic Roar - Winston Emote',
'Epic Excuse Me - Winston Highlight',
'Epic Glasses - Winston Highlight',
'Epic Primal Rage - Winston Highlight',
'Epic Desert - Winston Skin',
'Epic Horizon - Winston Skin',
'Epic Bring It On - Zarya Emote',
'Epic Crush You - Zarya Emote',
'Epic Pumping Iron - Zarya Emote',
'Epic Deadlift - Zarya Highlight',
'Epic Maximum Charge - Zarya Highlight',
'Epic This Is Strength - Zarya Highlight',
'Epic Dawn - Zarya Skin',
'Epic Midnight - Zarya Skin',
'Epic Focusing - Zenyatta Emote',
'Epic Round Of Applause - Zenyatta Emote',
'Epic Taunt - Zenyatta Emote',
'Epic Focused - Zenyatta Highlight',
'Epic Harmony And Discord - Zenyatta Highlight',
'Epic Transcendence - Zenyatta Highlight',
'Epic Ascendant - Zenyatta Skin',
'Epic Harmonious - Zenyatta Skin',
'LEGENDARY Steambot - Bastion Skin',
'LEGENDARY Woodbot - Bastion Skin',
'LEGENDARY Antique - Bastion Skin',
'LEGENDARY Gearbot - Bastion Skin',
'LEGENDARY Junker - D.Va Skin',
'LEGENDARY B.Va - D.Va Skin',
'LEGENDARY Scavenger - D.Va Skin',
'LEGENDARY Junebug - D.Va Skin',
'LEGENDARY Sparrow - Genji Skin',
'LEGENDARY Young Genji - Genji Skin',
'LEGENDARY Bedouin - Genji Skin',
'LEGENDARY Nomad - Genji Skin',
'LEGENDARY Young Hanzo - Hanzo Skin',
'LEGENDARY Young Master - Hanzo Skin',
'LEGENDARY Lone Wolf - Hanzo Skin',
'LEGENDARY Okami - Hanzo Skin',
'LEGENDARY Jester - Junkrat Skin',
'LEGENDARY Fool - Junkrat Skin',
'LEGENDARY Hayseed - Junkrat Skin',
'LEGENDARY Scarecrow - Junkrat Skin',
'LEGENDARY Hippityhop - Lucio Skin',
'LEGENDARY Ribbit - Lucio Skin',
'LEGENDARY Breakaway - Lucio Skin',
'LEGENDARY Slapshot - Lucio Skin',
'LEGENDARY Gambler - McCree Skin',
'LEGENDARY Mystery Man - McCree Skin',
'LEGENDARY RiverBoat - McCree Skin',
'LEGENDARY Vigilante - McCree Skin',
'LEGENDARY Firefighter - Mei Skin',
'LEGENDARY Rescue Mei - Mei Skin',
'LEGENDARY Abominable - Mei Skin',
'LEGENDARY Yeti Hunter - Mei Skin',
'LEGENDARY Sigrun - Mercy Skin',
'LEGENDARY Valkyrie - Mercy Skin',
'LEGENDARY Devil - Mercy Skin',
'LEGENDARY Imp - Mercy Skin',
'LEGENDARY Mechaqueen - Pharah Skin',
'LEGENDARY Raptorion - Pharah Skin',
'LEGENDARY Raindancer - Pharah Skin',
'LEGENDARY Thunderbird - Pharah Skin',
'LEGENDARY Plague Doctor - Reaper Skin',
'LEGENDARY El Blanco - Reaper Skin',
'LEGENDARY Mariachi - Reaper Skin',
'LEGENDARY Nevermore - Reaper Skin',
'LEGENDARY Blackhardt - Reinhardt Skin',
'LEGENDARY Bloodhardt - Reinhardt Skin',
'LEGENDARY Lionhardt - Reinhardt Skin',
'LEGENDARY Stonehardt - Reinhardt Skin',
'LEGENDARY Mako - Roadhog Skin',
'LEGENDARY Toa - Roadhog Skin',
'LEGENDARY Islander - Roadhog Skin',
'LEGENDARY Sharkbait - Roadhog Skin',
'LEGENDARY Commando - Soldier: 76 Skin',
'LEGENDARY Night Ops - Soldier: 76 Skin',
'LEGENDARY Daredevil - Soldier: 76 Skin',
'LEGENDARY Stunt Rider - Soldier: 76 Skin',
'LEGENDARY Architech - Symmetra Skin',
'LEGENDARY Devi - Symmetra Skin',
'LEGENDARY Goddess - Symmetra Skin',
'LEGENDARY Vishkar - Symmetra Skin',
'LEGENDARY Barbarossa - Torbjorn Skin',
'LEGENDARY Blackbeard - Torbjorn Skin',
'LEGENDARY Chopper - Torbjorn Skin',
'LEGENDARY Deadlock - Torbjorn Skin',
'LEGENDARY T. Racer - Tracer Skin',
'LEGENDARY Mach T - Tracer Skin',
'LEGENDARY Punk - Tracer Skin',
'LEGENDARY Ultraviolet - Tracer Skin',
'LEGENDARY Odette - Widowmaker Skin',
'LEGENDARY Odile - Widowmaker Skin',
'LEGENDARY Comtesse - Widowmaker Skin',
'LEGENDARY Huntress - Widowmaker Skin',
'LEGENDARY Explorer - Winston Skin',
'LEGENDARY Frogston - Winston Skin',
'LEGENDARY Undersea - Winston Skin',
'LEGENDARY Safari - Winston Skin',
'LEGENDARY Arctic - Zarya Skin',
'LEGENDARY Siberian Front - Zarya Skin',
'LEGENDARY Cyber Goth - Zarya Skin',
'LEGENDARY Industrial - Zarya Skin',
'LEGENDARY Djinyatta - Zenyatta Skin',
'LEGENDARY Ifrit - Zenyatta Skin',
'LEGENDARY Ra - Zenyatta Skin',
'LEGENDARY Sunyatta - Zenyatta Skin',
'Rare Birdwatching - Bastion Pose',
'Rare Pop Up - Bastion Pose',
'Rare Tank - Bastion Pose',
'Rare Dawn - Bastion Skin',
'Rare Meadow - Bastion Skin',
'Rare Sky - Bastion Skin',
'Rare Soot - Bastion Skin',
'Rare Bunny Hop - D.Va Emote',
'Rare Heartbreaker - D.Va Emote',
'Rare Party Time - D.Va Emote',
'Rare I Heart You - D.Va Pose',
'Rare Peace - D.Va Pose',
'Rare Sitting - D.Va Pose',
'Rare Blueberry - D.Va Skin',
'Rare Lemon-Lime- D.Va Skin',
'Rare Tangerine - D.Va Skin',
'Rare Watermelon - D.Va Skin',
'Rare Kneeling - Genji Pose',
'Rare Shuriken - Genji Pose',
'Rare Sword Stance - Genji Pose',
'Rare Azurite - Genji Skin',
'Rare Malachite - Genji Skin',
'Rare Ochre - Genji Skin',
'Rare Cinnabar - Genji Skin',
'Rare Confident - Hanzo Pose',
'Rare Kneeling - Hanzo Pose',
'Rare Over the Shoulder - Hanzo Pose',
'Rare Azuki - Hanzo Skin',
'Rare Kinoko - Hanzo Skin',
'Rare Midori - Hanzo Skin',
'Rare Sora - Hanzo Skin',
'Rare Itll Freeze That Way - Junkrat Pose',
'Rare Kneeling - Junkrat Pose',
'Rare Nyah Nyah - Junkrat Pose',
'Rare Bleached - Junkrat Skin',
'Rare Drowned - Junkrat Skin',
'Rare Irradiated - Junkrat Skin',
'Rare Rusted - Junkrat Skin',
'Rare Confident - Lucio Pose',
'Rare Grooving - Lucio Pose',
'Rare Ready for Action - Lucio Pose',
'Rare Azul - Lucio Skin',
'Rare Laranja - Lucio Skin',
'Rare Vermelho - Lucio Skin',
'Rare Roxo - Lucio Skin',
'Rare Contemplative - McCree Pose',
'Rare Over the Shoulder - McCree Pose',
'Rare Take it Easy - McCree Pose',
'Rare Ebony - McCree Skin',
'Rare Sage - McCree Skin',
'Rare Lake - McCree Skin',
'Rare Wheat - McCree Skin',
'Rare Casual - Mei Pose',
'Rare Hands on Hips - Mei Pose',
'Rare Kneeling - Mei Pose',
'Rare Jade - Mei Skin',
'Rare Persimmon - Mei Skin',
'Rare Heliotrope - Mei Skin',
'Rare Chrysanthemum - Mei Skin',
'Rare Angelic - Mercy Pose',
'Rare Carefree - Mercy Pose',
'Rare Ready for Battle - Mercy Pose',
'Rare Celestial - Mercy Skin',
'Rare Mist - Mercy Skin',
'Rare Orchid - Mercy Skin',
'Rare Vendant - Mercy Skin',
'Rare Guardian - Pharah Pose',
'Rare Jump Jet - Pharah Pose',
'Rare Kneeling - Pharah Pose',
'Rare Amethyst - Pharah Skin',
'Rare Copper - Pharah Skin',
'Rare Emerald - Pharah Skin',
'Rare Titanium - Pharah Skin',
'Rare Casual - Reaper Pose',
'Rare Enigmatic - Reaper Pose',
'Rare Menacing - Reaper Pose',
'Rare Blood - Reaper Skin',
'Rare Midnight - Reaper Skin',
'Rare Moss - Reaper Skin',
'Rare Royal - Reaper Skin',
'Rare Confident - Reinhardt Pose',
'Rare Flex - Reinhardt Pose',
'Rare LEGENDARY - Reinhardt Pose',
'Rare Brass - Reinhardt Skin',
'Rare Cobalt - Reinhardt Skin',
'Rare Copper - Reinhardt Skin',
'Rare Viridian - Reinhardt Skin',
'Rare Pointing to the Sky - Roadhog Pose',
'Rare Thumbs Up - Roadhog Pose',
'Rare Tuckered Out - Roadhog Pose',
'Rare Kiwi - Roadhog Skin',
'Rare Mud - Roadhog Skin',
'Rare Thistle - Roadhog Skin',
'Rare Sand - Roadhog Skin',
'Rare Fist Pump - Soldier: 76 Pose',
'Rare Locked and Loaded - Soldier: 76 Pose',
'Rare Soldier - Soldier: 76 Pose',
'Rare Olive - Soldier: 76 Skin',
'Rare Russet - Soldier: 76 Skin',
'Rare Jet - Soldier: 76 Skin',
'Rare Smoke - Soldier: 76 Skin',
'Rare Balance - Symmetra Pose',
'Rare Creation - Symmetra Pose',
'Rare Dance - Symmetra Pose',
'Rare Hyacinth - Symmetra Skin',
'Rare Cardamom - Symmetra Skin',
'Rare Saffron - Symmetra Skin',
'Rare Technomancer - Symmetra Skin',
'Rare Hammer - Torbjorn Pose',
'Rare Sitting Pretty - Torbjorn Pose',
'Rare Take Five - Torbjorn Pose',
'Rare Bla - Torbjorn Skin',
'Rare Citron - Torbjorn Skin',
'Rare Gron - Torbjorn Skin',
'Rare Plommon - Torbjorn Skin',
'Rare Over the Shoulder - Tracer Pose',
'Rare Salute - Tracer Pose',
'Rare Sitting - Tracer Pose',
'Rare Royal Blue - Tracer Skin',
'Rare Neon Green - Tracer Skin',
'Rare Hot Pink - Tracer Skin',
'Rare Electric Purple - Tracer Skin',
'Rare Activating Visor - Widowmaker Pose',
'Rare Gaze - Widowmaker Pose',
'Rare Over the Shoulder - Widowmaker Pose',
'Rare Ciel - Widowmaker Skin',
'Rare Nuit - Widowmaker Skin',
'Rare Vert - Widowmaker Skin',
'Rare Rose - Widowmaker Skin',
'Rare Beast - Winston Pose',
'Rare Glasses - Winston Pose',
'Rare The Thinker - Winston Pose',
'Rare Banana - Winston Skin',
'Rare Forest - Winston Skin',
'Rare Red Planet - Winston Skin',
'Rare Atmosphere - Winston Skin',
'Rare Casual - Zarya Pose',
'Rare Check Out This Gun - Zarya Pose',
'Rare Flexing - Zarya Pose',
'Rare Brick - Zarya Skin',
'Rare Taiga - Zarya Skin',
'Rare Violet - Zarya Skin',
'Rare Goldenrod - Zarya Skin',
'Rare Balance - Zenyatta Pose',
'Rare Harmony - Zenyatta Pose',
'Rare Peace - Zenyatta Pose',
'Rare Air - Zenyatta Skin',
'Rare Earth - Zenyatta Skin',
'Rare Leaf - Zenyatta Skin',
'Rare Water - Zenyatta Skin',
'Rare 50 Coins',
'Epic 150 Coins',
'LEGENDARY 500 Coins' 
];
var specweights = [
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
7,
2
];

var crate
var openSound = new Audio('open-box.ogg');
var results = [];
var isRunning = false;


$.fn.extend({
    animateCss: function (animationName) {
        var animationEnd = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
        $(this).addClass('animated ' + animationName).one(animationEnd, function() {
            $(this).removeClass('animated ' + animationName);
        });
    }
});


function openBox(){
  
  if(isRunning == false){
    //Reset Crate
    results = [];
    setTimeout(delay,1750);
    setTimeout(hideBox,750);
    setTimeout(deleteCards,1050);
    openSound.play();
    $('#box').animateCss('bounceOutUp');
    $('#item0').animateCss('bounceOutUp');
    $('#item1').animateCss('bounceOutUp');
    $('#item2').animateCss('bounceOutUp');
    $('#item3').animateCss('bounceOutUp');
    
    isRunning = true;
  }
}

function deleteCards(){
  $( "#item0" ).remove();
  $( "#item1" ).remove();
  $( "#item2" ).remove();
  $( "#item3" ).remove();
}

function hideBox(){
  $( "#box" ).remove();
}

function delay(){
  setTimeout(setBox,250);
  
}

function setBox(){
  

  for(i = 0; i < 3; i++){
    //Randomize Loot
    crate = chance.weighted(loot, weights);
    results.push(crate);
  }
  
  cratespec = chance.weighted(specloot, specweights);
  results.push(cratespec);  
  
  endresults = chance.shuffle(results);
  displayBox();
  
}

function displayBox(){
  //Add to list
  for(i = 0; i < endresults.length; i++){
    var ul = document.getElementById("crate");
    var li = document.createElement("li");
    li.appendChild(document.createTextNode(endresults[i]));
    li.setAttribute("id", "item" + i);
    ul.appendChild(li);

    //Check Quality and Strip
    var str = $("#item" + i).text();
     if(endresults[i].indexOf("Normal") !=-1){
      $("#item" + i).addClass("normal animated bounceInDown");
      $("#item" + i).text(str.substring(7));
    }
    if (endresults[i].indexOf("Rare") !=-1){
      $("#item" + i).addClass("rare animated bounceInDown");
      $("#item" + i).text(str.substring(5));
    }
    if(endresults[i].indexOf("Epic") !=-1){
      $("#item" + i).addClass("epic animated bounceInDown");
      $("#item" + i).text(str.substring(5));
    }
    if(endresults[i].indexOf("LEGENDARY") !=-1){
      $("#item" + i).addClass("legendary animated bounceInDown");
      $("#item" + i).text(str.substring(10));
    }

    //Check Hero
    //Generic
    if(endresults[i].indexOf("Spray") || endresults[i].indexOf("Coins") !=-1){
      $("#item" + i).addClass("generic");
    }
    //bastion
    if(endresults[i].indexOf("Bastion") !=-1){
      $("#item" + i).addClass("bastion");
    }
    //dva
    if(endresults[i].indexOf("D.Va") !=-1){
      $("#item" + i).addClass("dva");
    }
    //genji
    if(endresults[i].indexOf("Genji") !=-1){
      $("#item" + i).addClass("genji");
    }
    //hanzo
    if(endresults[i].indexOf("Hanzo") !=-1){
      $("#item" + i).addClass("hanzo");
    }
    //junkrat
    if(endresults[i].indexOf("Junkrat") !=-1){
      $("#item" + i).addClass("junkrat");
    }
    //lucio
    if(endresults[i].indexOf("Lucio") !=-1){
      $("#item" + i).addClass("lucio");
    }
    //McCree
    if(endresults[i].indexOf("McCree") !=-1){
      $("#item" + i).addClass("mccree");
    }
    //Reaper
    if(endresults[i].indexOf("Reaper") !=-1){
      $("#item" + i).addClass("reaper");
    }
    //Mei
    if(endresults[i].indexOf("Mei") !=-1){
      $("#item" + i).addClass("mei");
    }
    //Mercy
    if(endresults[i].indexOf("Mercy") !=-1){
      $("#item" + i).addClass("mercy");
    }
    //Pharah
    if(endresults[i].indexOf("Pharah") !=-1){
      $("#item" + i).addClass("pharah");
    }
    //Reinhardt
    if(endresults[i].indexOf("Reinhardt") !=-1){
      $("#item" + i).addClass("reinhardt");
    }
    //Roadhog
    if(endresults[i].indexOf("Roadhog") !=-1){
      $("#item" + i).addClass("roadhog");
    }
    //Solider76
    if(endresults[i].indexOf("Soldier: 76") !=-1){
      $("#item" + i).addClass("soldier");
    }
    //Symmetra
    if(endresults[i].indexOf("Symmetra") !=-1){
      $("#item" + i).addClass("symmetra");
    }
    //Torbjorn
    if(endresults[i].indexOf("Torbjorn") !=-1){
      $("#item" + i).addClass("torbjorn");
    }
    //Tracer
    if(endresults[i].indexOf("Tracer") !=-1){
      $("#item" + i).addClass("tracer");
    }
    //Widowmaker
    if(endresults[i].indexOf("Widowmaker") !=-1){
      $("#item" + i).addClass("widowmaker");
    }
    //Winston
    if(endresults[i].indexOf("Winston") !=-1){
      $("#item" + i).addClass("winston");
    }
    //Zarya
    if(endresults[i].indexOf("Zarya") !=-1){
      $("#item" + i).addClass("zarya");
    }
    //Zenyatta
    if(endresults[i].indexOf("Zenyatta") !=-1){
      $("#item" + i).addClass("zenyatta");
    }

  }

  isRunning = false;
}

function shakeBox(){
  $("#box").addClass("shakebox");
  setTimeout(removeShake,820);
}

function removeShake(){
  $("#box").removeClass("shakebox");
  setTimeout(shakeBox,1820);
}
