var specloot = [
'Epic Alert! Alert! - Bastion Emote',
'Epic Chortle - Bastion Emote',
'Epic Dizzy - Bastion Emote',
'Epic Rest Mode - Bastion Emote',
'Epic Robot - Bastion Emote',
'Epic Bullet Rain - Bastion Highlight',
'Epic Ganymede - Bastion Highlight',
'Epic On Guard - Bastion Highlight',
'Epic Omnic Crisis - Bastion Skin',
'Epic Defense Matrix - Bastion Skin',
'Epic Eject - D.Va Highlight',
'Epic Lying Around - D.Va Highlight',
'Epic Meka Activated - D.Va Highlight',
'Epic Carbon Fiber - D.Va Skin',
'Epic White Rabbit - D.Va Skin',
'Epic Challenge - Genji Emote',
'Epic Cutting Edge - Genji Emote',
'Epic Amusing - Genji Emote',
'Epic Meditate - Genji Emote',
'Epic Salute - Genji Emote',
'Epic Shuriken - Genji Highlight',
'Epic Unsheathing the Sword - Genji Highlight',
'Epic Warriors Salute - Genji Highlight',
'Epic Carbon Fiber - Genji Skin',
'Epic Chrome - Genji Skin',
'Epic Beckon - Hanzo Emote',
'Epic Chuckle - Hanzo Emote',
'Epic Meditate - Hanzo Emote',
'Epic Brush Shoulder - Hanzo Emote',
'Epic Victory - Hanzo Emote',
'Epic Backflip - Hanzo Highlight',
'Epic My Aim is True - Hanzo Highlight',
'Epic Superior - Hanzo Highlight',
'Epic Cloud - Hanzo Skin',
'Epic Dragon - Hanzo Skin',
'Epic Juggling - Junkrat Emote',
'Epic Puppet - Junkrat Emote',
'Epic Cant Deal - Junkrat Emote',
'Epic Lounging - Junkrat Emote',
'Epic Vaudeville - Junkrat Emote',
'Epic Im Flying! - Junkrat Highlight',
'Epic Rip-Tire- Junkrat Highlight',
'Epic Unfortunate - Junkrat Highlight',
'Epic Jailbird - Junkrat Skin',
'Epic Toasted - Junkrat Skin',
'Epic Capoeira - Lucio Emote',
'Epic In The Groove - Lucio Emote',
'Epic Chilling - Lucio Emote',
'Epic Knee Slapper - Lucio Emote',
'Epic Nah! - Lucio Emote',
'Epic Drop The Beat - Lucio Highlight',
'Epic Freestyle - Lucio Highlight',
'Epic In The Groove - Lucio Highlight',
'Epic Auditva - Lucio Skin',
'Epic Synaesthesia - Lucio Skin',
'Epic Gunspinning - McCree Emote',
'Epic Joker - McCree Emote',
'Epic Take A Load Off - McCree Emote',
'Epic Hat Tip - McCree Emote',
'Epic Spit - McCree Emote',
'Epic Rolling Into Action - McCree Highlight',
'Epic The Duel - McCree Highlight',
'Epic The Names McCree - McCree Highlight',
'Epic On The Range - McCree Skin',
'Epic White Hat - McCree Skin',
'Epic Companion - Mei Emote',
'Epic Giggle - Mei Emote',
'Epic Kneel - Mei Emote',
'Epic Spray - Mei Emote',
'Epic Yaaaaaaaaaaay! - Mei Emote',
'Epic Frosty :) - Mei Highlight',
'Epic Going Up! - Mei Highlight',
'Epic Skating Around - Mei Highlight',
'Epic Earthen - Mei Skin',
'Epic Snow Plum - Mei Skin',
'Epic Applause - Mercy Emote',
'Epic Caduceus - Mercy Emote',
'Epic No Pulse - Mercy Emote',
'Epic Relax - Mercy Emote',
'Epic The Best Medicine - Mercy Emote',
'Epic Battle Angel - Mercy Highlight',
'Epic Guardian Angel - Mercy Highlight',
'Epic Heroes Never Die - Mercy Highlight',
'Epic Amber - Mercy Skin',
'Epic Cobalt - Mercy Skin',
'Epic Cheer - Pharah Emote',
'Epic Chuckle - Pharah Emote',
'Epic Take A Knee - Pharah Emote',
'Epic Flourish - Pharah Emote',
'Epic Knuckles - Pharah Emote',
'Epic Barrage - Pharah Highlight',
'Epic Mission Complete - Pharah Highlight',
'Epic Touchdown - Pharah Highlight',
'Epic Anubis - Pharah Skin',
'Epic Jackal - Pharah Skin',
'Epic Not Impressed - Reaper Emote',
'Epic Slice - Reaper Emote',
'Epic Cackle - Reaper Emote',
'Epic Take A Knee - Reaper Emote',
'Epic Slow Clap - Reaper Emote',
'Epic Death Blossom - Reaper Highlight',
'Epic Executioner - Reaper Highlight',
'Epic Shadow Step - Reaper Highlight',
'Epic Desert - Reaper Skin',
'Epic Wight - Reaper Skin',
'Epic Flex - Reinhardt Emote',
'Epic Uproarious - Reinhardt Emote',
'Epic Kneel - Reinhardt Emote',
'Epic Taunt - Reinhardt Emote',
'Epic Warriors Salute - Reinhardt Emote',
'Epic Charge - Reinhardt Highlight',
'Epic Hammer Down - Reinhardt Highlight',
'Epic More Stretching Required - Reinhardt Highlight',
'Epic Bundeswehr - Reinhardt Skin',
'Epic Paragon - Reinhardt Skin',
'Epic Boo! - Roadhog Emote',
'Epic Can Crusher - Roadhog Emote',
'Epic Headbanging - Roadhog Emote',
'Epic Tuckered Out - Roadhog Emote',
'Epic Belly Laugh - Roadhog Emote',
'Epic Little Piggy - Roadhog Highlight',
'Epic Say "Cheese" - Roadhog Highlight',
'Epic Whole Hog - Roadhog Highlight',
'Epic Pigpen - Roadhog Skin',
'Epic Stitched - Roadhog Skin',
'Epic Fist - Soldier: 76 Emote',
'Epic Amused - Soldier: 76 Emote',
'Epic Take A Knee - Soldier: 76 Emote',
'Epic I See You - Soldier: 76 Emote',
'Epic Locked And Loaded - Soldier: 76 Emote',
'Epic Helix - Soldier: 76 Highlight',
'Epic Looking At You - Soldier: 76 Highlight',
'Epic Target Rich Environment - Soldier: 76 Highlight',
'Epic Bone - Soldier: 76 Skin',
'Epic Golden - Soldier: 76 Skin',
'Epic Clap - Symmetra Emote',
'Epic Flow - Symmetra Emote',
'Epic Have A Seat - Symmetra Emote',
'Epic Snicker - Symmetra Emote',
'Epic Insignificant - Symmetra Emote',
'Epic Askew - Symmetra Highlight',
'Epic Dance - Symmetra Highlight',
'Epic My Reality - Symmetra Highlight',
'Epic Regal - Symmetra Skin',
'Epic Utopaea - Symmetra Skin',
'Epic Clicking Heels - Torbjorn Emote',
'Epic Fisticuffs - Torbjorn Emote',
'Epic Guffaw - Torbjorn Emote',
'Epic Taking A Break - Torbjorn Emote',
'Epic Overload - Torbjorn Emote',
'Epic In Your Face - Torbjorn Highlight',
'Epic Refreshing - Torbjorn Highlight',
'Epic Ride Em - Torbjorn Highlight',
'Epic Cathode - Torbjorn Skin',
'Epic Woodclad - Torbjorn Skin',
'Epic Cheer - Tracer Emote',
'Epic Laughing - Tracer Emote',
'Epic Spin - Tracer Emote',
'Epic Sitting Around... - Tracer Emote',
'Epic Backflip - Tracer Highlight',
'Epic Just In Time - Tracer Highlight',
'Epic Serious Business - Tracer Highlight',
'Epic Posh - Tracer Skin',
'Epic Sporty - Tracer Skin',
'Epic Curtain Call - Widowmaker Emote',
'Epic Delighted - Widowmaker Emote',
'Epic At Rest - Widowmaker Emote',
'Epic Shot Dead - Widowmaker Emote',
'Epic Widows Kiss - Widowmaker Emote',
'Epic Hanging Around - Widowmaker Highlight',
'Epic I See You... - Widowmaker Highlight',
'Epic Swinging Into Action - Widowmaker Highlight',
'Epic Winter - Widowmaker Skin',
'Epic Patina - Widowmaker Skin',
'Epic Monkey Business - Winston Emote',
'Epic Peanut Butter? - Winston Emote',
'Epic Roar - Winston Emote',
'Epic Sitting Around - Winston Emote',
'Epic Laughing Matter - Winston Emote',
'Epic Excuse Me - Winston Highlight',
'Epic Glasses - Winston Highlight',
'Epic Primal Rage - Winston Highlight',
'Epic Desert - Winston Skin',
'Epic Horizon - Winston Skin',
'Epic Bring It On - Zarya Emote',
'Epic Crush You - Zarya Emote',
'Epic Pumping Iron - Zarya Emote',
'Epic Deadlift - Zarya Highlight',
'Epic Maximum Charge - Zarya Highlight',
'Epic This Is Strength - Zarya Highlight',
'Epic Dawn - Zarya Skin',
'Epic Midnight - Zarya Skin',
'Epic Focusing - Zenyatta Emote',
'Epic Meditate - Zenyatta Emote',
'Epic Tickled - Zenyatta Emote',
'Epic Round Of Applause - Zenyatta Emote',
'Epic Taunt - Zenyatta Emote',
'Epic Focused - Zenyatta Highlight',
'Epic Harmony And Discord - Zenyatta Highlight',
'Epic Transcendence - Zenyatta Highlight',
'Epic Ascendant - Zenyatta Skin',
'Epic Harmonious - Zenyatta Skin',
'Lgnd Steambot - Bastion Skin',
'Lgnd Woodbot - Bastion Skin',
'Lgnd Antique - Bastion Skin',
'Lgnd Gearbot - Bastion Skin',
'Lgnd Junker - D.Va Skin',
'Lgnd B.Va - D.Va Skin',
'Lgnd Scavenger - D.Va Skin',
'Lgnd Junebug - D.Va Skin',
'Lgnd Sparrow - Genji Skin',
'Lgnd Young Genji - Genji Skin',
'Lgnd Bedouin - Genji Skin',
'Lgnd Nomad - Genji Skin',
'Lgnd Young Hanzo - Hanzo Skin',
'Lgnd Young Master - Hanzo Skin',
'Lgnd Lone Wolf - Hanzo Skin',
'Lgnd Okami - Hanzo Skin',
'Lgnd Jester - Junkrat Skin',
'Lgnd Fool - Junkrat Skin',
'Lgnd Hayseed - Junkrat Skin',
'Lgnd Scarecrow - Junkrat Skin',
'Lgnd Hippityhop - Lucio Skin',
'Lgnd Ribbit - Lucio Skin',
'Lgnd Breakaway - Lucio Skin',
'Lgnd Slapshot - Lucio Skin',
'Lgnd Gambler - McCree Skin',
'Lgnd Mystery Man - McCree Skin',
'Lgnd RiverBoat - McCree Skin',
'Lgnd Vigilante - McCree Skin',
'Lgnd Firefighter - Mei Skin',
'Lgnd Rescue Mei - Mei Skin',
'Lgnd Abominable - Mei Skin',
'Lgnd Yeti Hunter - Mei Skin',
'Lgnd Sigrun - Mercy Skin',
'Lgnd Valkyrie - Mercy Skin',
'Lgnd Devil - Mercy Skin',
'Lgnd Imp - Mercy Skin',
'Lgnd Mechaqueen - Pharah Skin',
'Lgnd Raptorion - Pharah Skin',
'Lgnd Raindancer - Pharah Skin',
'Lgnd Thunderbird - Pharah Skin',
'Lgnd Plague Doctor - Reaper Skin',
'Lgnd El Blanco - Reaper Skin',
'Lgnd Mariachi - Reaper Skin',
'Lgnd Nevermore - Reaper Skin',
'Lgnd Blackhardt - Reinhardt Skin',
'Lgnd Greifhardt - Reinhardt Skin',
'Lgnd Balderich - Reinhardt Skin',
'Lgnd Bloodhardt - Reinhardt Skin',
'Lgnd Lionhardt - Reinhardt Skin',
'Lgnd Stonehardt - Reinhardt Skin',
'Lgnd Mako - Roadhog Skin',
'Lgnd Toa - Roadhog Skin',
'Lgnd Islander - Roadhog Skin',
'Lgnd Sharkbait - Roadhog Skin',
'Lgnd Commando - Soldier: 76 Skin',
'Lgnd Night Ops - Soldier: 76 Skin',
'Lgnd Daredevil - Soldier: 76 Skin',
'Lgnd Stunt Rider - Soldier: 76 Skin',
'Lgnd Architech - Symmetra Skin',
'Lgnd Devi - Symmetra Skin',
'Lgnd Goddess - Symmetra Skin',
'Lgnd Vishkar - Symmetra Skin',
'Lgnd Barbarossa - Torbjorn Skin',
'Lgnd Blackbeard - Torbjorn Skin',
'Lgnd Chopper - Torbjorn Skin',
'Lgnd Deadlock - Torbjorn Skin',
'Lgnd T. Racer - Tracer Skin',
'Lgnd Mach T - Tracer Skin',
'Lgnd Punk - Tracer Skin',
'Lgnd Ultraviolet - Tracer Skin',
'Lgnd Odette - Widowmaker Skin',
'Lgnd Odile - Widowmaker Skin',
'Lgnd Comtesse - Widowmaker Skin',
'Lgnd Huntress - Widowmaker Skin',
'Lgnd Explorer - Winston Skin',
'Lgnd Frogston - Winston Skin',
'Lgnd Undersea - Winston Skin',
'Lgnd Safari - Winston Skin',
'Lgnd Arctic - Zarya Skin',
'Lgnd Siberian Front - Zarya Skin',
'Lgnd Cyber Goth - Zarya Skin',
'Lgnd Industrial - Zarya Skin',
'Lgnd Djinyatta - Zenyatta Skin',
'Lgnd Ifrit - Zenyatta Skin',
'Lgnd Ra - Zenyatta Skin',
'Lgnd Sunyatta - Zenyatta Skin',
'Rare Birdwatching - Bastion Pose',
'Rare Pop Up - Bastion Pose',
'Rare Tank - Bastion Pose',
'Rare Dawn - Bastion Skin',
'Rare Meadow - Bastion Skin',
'Rare Sky - Bastion Skin',
'Rare Soot - Bastion Skin',
'Epic Bunny Hop - D.Va Emote',
'Epic Heartbreaker - D.Va Emote',
'Epic ^o^ - D.Va Emote',
'Epic Party Time - D.Va Emote',
'Lgnd Game On - D.Va Emote',
'Rare I Heart You - D.Va Pose',
'Rare Peace - D.Va Pose',
'Rare Sitting - D.Va Pose',
'Rare Blueberry - D.Va Skin',
'Rare Lemon-Lime - D.Va Skin',
'Rare Tangerine - D.Va Skin',
'Rare Watermelon - D.Va Skin',
'Rare Kneeling - Genji Pose',
'Rare Shuriken - Genji Pose',
'Rare Sword Stance - Genji Pose',
'Rare Azurite - Genji Skin',
'Rare Malachite - Genji Skin',
'Rare Ochre - Genji Skin',
'Rare Cinnabar - Genji Skin',
'Rare Confident - Hanzo Pose',
'Rare Kneeling - Hanzo Pose',
'Rare Over the Shoulder - Hanzo Pose',
'Rare Azuki - Hanzo Skin',
'Rare Kinoko - Hanzo Skin',
'Rare Midori - Hanzo Skin',
'Rare Sora - Hanzo Skin',
'Rare Itll Freeze That Way - Junkrat Pose',
'Rare Kneeling - Junkrat Pose',
'Rare Nyah Nyah - Junkrat Pose',
'Rare Bleached - Junkrat Skin',
'Rare Drowned - Junkrat Skin',
'Rare Irradiated - Junkrat Skin',
'Rare Rusted - Junkrat Skin',
'Rare Confident - Lucio Pose',
'Rare Grooving - Lucio Pose',
'Rare Ready for Action - Lucio Pose',
'Rare Azul - Lucio Skin',
'Rare Laranja - Lucio Skin',
'Rare Vermelho - Lucio Skin',
'Rare Roxo - Lucio Skin',
'Rare Contemplative - McCree Pose',
'Rare Over the Shoulder - McCree Pose',
'Rare Take it Easy - McCree Pose',
'Rare Ebony - McCree Skin',
'Rare Sage - McCree Skin',
'Rare Lake - McCree Skin',
'Rare Wheat - McCree Skin',
'Rare Casual - Mei Pose',
'Rare Hands on Hips - Mei Pose',
'Rare Kneeling - Mei Pose',
'Rare Jade - Mei Skin',
'Rare Persimmon - Mei Skin',
'Rare Heliotrope - Mei Skin',
'Rare Chrysanthemum - Mei Skin',
'Rare Angelic - Mercy Pose',
'Rare Carefree - Mercy Pose',
'Rare Ready for Battle - Mercy Pose',
'Rare Celestial - Mercy Skin',
'Rare Mist - Mercy Skin',
'Rare Orchid - Mercy Skin',
'Rare Vendant - Mercy Skin',
'Rare Guardian - Pharah Pose',
'Rare Jump Jet - Pharah Pose',
'Rare Kneeling - Pharah Pose',
'Rare Amethyst - Pharah Skin',
'Rare Copper - Pharah Skin',
'Rare Emerald - Pharah Skin',
'Rare Titanium - Pharah Skin',
'Rare Casual - Reaper Pose',
'Rare Enigmatic - Reaper Pose',
'Rare Menacing - Reaper Pose',
'Rare Blood - Reaper Skin',
'Rare Midnight - Reaper Skin',
'Rare Moss - Reaper Skin',
'Rare Royal - Reaper Skin',
'Rare Confident - Reinhardt Pose',
'Rare Flex - Reinhardt Pose',
'Rare Legendary - Reinhardt Pose',
'Rare Brass - Reinhardt Skin',
'Rare Cobalt - Reinhardt Skin',
'Rare Copper - Reinhardt Skin',
'Rare Viridian - Reinhardt Skin',
'Rare Pointing to the Sky - Roadhog Pose',
'Rare Thumbs Up - Roadhog Pose',
'Rare Tuckered Out - Roadhog Pose',
'Rare Kiwi - Roadhog Skin',
'Rare Mud - Roadhog Skin',
'Rare Thistle - Roadhog Skin',
'Rare Sand - Roadhog Skin',
'Rare Fist Pump - Soldier: 76 Pose',
'Rare Locked and Loaded - Soldier: 76 Pose',
'Rare Soldier - Soldier: 76 Pose',
'Rare Olive - Soldier: 76 Skin',
'Rare Russet - Soldier: 76 Skin',
'Rare Jet - Soldier: 76 Skin',
'Rare Smoke - Soldier: 76 Skin',
'Rare Balance - Symmetra Pose',
'Rare Creation - Symmetra Pose',
'Rare Dance - Symmetra Pose',
'Rare Hyacinth - Symmetra Skin',
'Rare Cardamom - Symmetra Skin',
'Rare Saffron - Symmetra Skin',
'Rare Technomancer - Symmetra Skin',
'Rare Hammer - Torbjorn Pose',
'Rare Sitting Pretty - Torbjorn Pose',
'Rare Take Five - Torbjorn Pose',
'Rare Bla - Torbjorn Skin',
'Rare Citron - Torbjorn Skin',
'Rare Gron - Torbjorn Skin',
'Rare Plommon - Torbjorn Skin',
'Rare Over the Shoulder - Tracer Pose',
'Rare Salute - Tracer Pose',
'Rare Sitting - Tracer Pose',
'Rare Royal Blue - Tracer Skin',
'Rare Neon Green - Tracer Skin',
'Rare Hot Pink - Tracer Skin',
'Rare Electric Purple - Tracer Skin',
'Rare Activating Visor - Widowmaker Pose',
'Rare Gaze - Widowmaker Pose',
'Rare Over the Shoulder - Widowmaker Pose',
'Rare Ciel - Widowmaker Skin',
'Rare Nuit - Widowmaker Skin',
'Rare Vert - Widowmaker Skin',
'Rare Rose - Widowmaker Skin',
'Rare Beast - Winston Pose',
'Rare Glasses - Winston Pose',
'Rare The Thinker - Winston Pose',
'Rare Banana - Winston Skin',
'Rare Forest - Winston Skin',
'Rare Red Planet - Winston Skin',
'Rare Atmosphere - Winston Skin',
'Rare Casual - Zarya Pose',
'Rare Check Out This Gun - Zarya Pose',
'Rare Flexing - Zarya Pose',
'Rare Brick - Zarya Skin',
'Rare Taiga - Zarya Skin',
'Rare Violet - Zarya Skin',
'Rare Goldenrod - Zarya Skin',
'Rare Balance - Zenyatta Pose',
'Rare Harmony - Zenyatta Pose',
'Rare Peace - Zenyatta Pose',
'Rare Air - Zenyatta Skin',
'Rare Earth - Zenyatta Skin',
'Rare Leaf - Zenyatta Skin',
'Rare Water - Zenyatta Skin',
'Rare 50 Coins',
'Epic 150 Coins',
'Lgnd 500 Coins',
'Epic Tea Time - Ana Emote',
'Epic Disapproving - Ana Emote',
'Epic Not Impressed - Ana Emote',
'Epic Protector - Ana Emote',
'Epic Take A Knee - Ana Emote',
'Epic Shh... - Ana Highlight',
'Epic Guardian - Ana Highlight',
'Epic Locked On - Ana Highlight',
'Epic Shrike - Ana Skin',
'Epic Merciful- Ana Skin',
'Lgnd Horus - Ana Skin',
'Lgnd Wadjet - Ana Skin',
'Lgnd Wasteland - Ana Skin',
'Lgnd Captain Amari - Ana Skin',
'Rare Seated - Ana Pose',
'Rare Mission Complete - Ana Pose',
'Rare Protector - Ana Pose',
'Rare Garnet - Ana Skin',
'Rare Citrine - Ana Skin',
'Rare Peridot - Ana Skin',
'Rare Turquoise - Ana Skin',
'Epic Amused - Sombra Emote',
'Epic Hold On - Sombra Emote',
'Epic Masterpiece - Sombra Emote',
'Epic Hacking - Sombra Highlight',
'Epic Pulse - Sombra Highlight',
'Epic Undetected - Sombra Highlight',
'Epic Glitch - Sombra Skin',
'Epic Virus - Sombra Skin',
'Lgnd Azucar - Sombra Skin',
'Lgnd Los Muertos - Sombra Skin',
'Lgnd Augmented - Sombra Skin',
'Lgnd Cyberspace - Sombra Skin',
'Rare Kneeling - Sombra Pose',
'Rare Hacked - Sombra Pose',
'Rare Rising - Sombra Pose',
'Rare Cidro - Sombra Skin',
'Rare Incendio - Sombra Skin',
'Rare Mar - Sombra Skin',
'Rare Noche - Sombra Skin',
'Epic Camouflage - Orisa Skin',
'Epic OR15 - Orisa Skin',
'Epic Camouflage - Orisa Skin',
'Epic Cheer - Orisa Emote',
'Epic Halt! - Orisa Emote',
'Epic Kicking Dirt - Orisa Emote',
'Lgnd Dynastinae - Orisa Skin',
'Lgnd Megasoma - Orisa Skin',
'Lgnd Carbon Fiber - Orisa Skin',
'Lgnd Protector - Orisa Skin',
'Rare Dawn - Orisa Skin',
'Rare Plains - Orisa Skin',
'Rare Sunrise - Orisa Skin',
'Rare Twilight - Orisa Skin',
'Rare Flex - Orisa Pose',
'Rare Halt! - Orisa Pose',
'Epic Keeping You Safe - Orisa Highlight',
'Epic Oh! - Orisa Highlight',
'Epic Supercharger - Orisa Highlight'
];

var specweights = [
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
2,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
32,
7,
2,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
32,
32,
32,
32,
32,
32,
32,
7,
7,
7,
7,
7,
7,
2,
2,
2,
2,
32,
32,
32,
32,
32,
32,
7,
7,
7
];