title: matou.io | Matt Marineau
author: Matthew Marineau
email: hello@matou.io
twitter_username: omgmrm
github_username:  matoululu

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact

kramdown:
  input: GFM
  syntax_highlighter: rouge