title: matou.io | Matt Marineau
author: Matthew Marineau
email: hello@matou.io
twitter_username: omgmrm
github_username:  matoululu


# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact